"use client";
/* eslint-disable @next/next/no-img-element -- favicon previews may use ICO and cache-busted remote URLs. */
import { useState } from "react";
import type { PublicSiteSettings } from "@/lib/site-settings";

function put(file: File, url: string) { return fetch(url, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); }
export default function FaviconManager({ initialSettings }: { initialSettings: PublicSiteSettings }) {
  const [settings, setSettings] = useState(initialSettings); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function upload(file: File) { setBusy(true); setMessage(null); try { const bitmap = await createImageBitmap(file); if (bitmap.width !== bitmap.height || bitmap.width < 256) throw new Error("Choose a square PNG at least 256 × 256 pixels."); const prepared = await fetch("/api/admin/site-settings/favicon/presign", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fileName: file.name, fileType: file.type, fileSize: file.size }) }); const data = await prepared.json(); if (!prepared.ok || !data.success) throw new Error(data.error || "Unable to prepare favicon."); const sent = await put(file, data.upload.uploadUrl); if (!sent.ok) throw new Error("Cloud storage rejected the favicon upload."); const next = { ...settings, faviconStorageKey: data.upload.key, faviconUrl: data.upload.publicUrl }; const saved = await fetch("/api/admin/site-settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(next) }); const result = await saved.json(); if (!saved.ok || !result.success) throw new Error(result.error || "Unable to publish favicon."); setSettings(result.settings); setMessage("Favicon published. Browser tabs may take a moment to refresh their cache."); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Unable to publish favicon."); } finally { setBusy(false); } }
  return <section className="rounded-2xl border border-white/[0.08] bg-[#111] p-6 lg:p-8"><div className="grid gap-7 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-[0.54rem] font-semibold uppercase tracking-[0.18em] text-[var(--helios-orange)]">Browser identity</p><h2 className="mt-3 text-2xl font-light text-white">Favicon manager</h2><p className="mt-3 max-w-lg text-sm leading-6 text-white/40">Upload one square PNG. Helios publishes it for standard browser, shortcut, and Apple touch icon use with automatic cache-busting.</p></div><div className="rounded-2xl border border-white/[0.08] bg-black/25 p-5"><div className="flex items-center gap-5"><div className="flex h-16 w-16 items-center justify-center overflow-hidden rounded-xl border border-white/10 bg-white"><img src={settings.faviconUrl || "/favicon.ico"} alt="Current favicon preview" className="h-12 w-12 object-contain" /></div><div><p className="text-sm text-white/65">Current favicon</p><p className="mt-1 text-xs text-white/30">Square PNG · minimum 256 × 256</p></div></div><label className={`admin-btn-primary mt-5 cursor-pointer ${busy ? "pointer-events-none opacity-40" : ""}`}>{busy ? "Publishing…" : settings.faviconUrl ? "Replace favicon" : "Upload favicon"}<input type="file" accept="image/png" className="sr-only" disabled={busy} onChange={event => { const file = event.target.files?.[0]; if (file) void upload(file); event.target.value = ""; }} /></label>{message && <p role="status" className="mt-4 text-sm text-white/45">{message}</p>}</div></div></section>;
}
