"use client";
import { useState } from "react";
import type { PublicSiteSettings } from "@/lib/site-settings";

export default function SiteSettingsForm({ initialSettings }: { initialSettings: PublicSiteSettings }) {
  const [settings, setSettings] = useState(initialSettings); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  function update(key: keyof PublicSiteSettings, value: string) { setSettings((current) => ({ ...current, [key]: value || null })); }
  async function save() { setSaving(true); setMessage(null); try { const response = await fetch("/api/admin/site-settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || "Unable to save settings."); setSettings(data.settings); setMessage("Global settings saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save settings."); } finally { setSaving(false); } }
  const groups = [
    { title: "Business and contact", fields: [["businessName","Business name"],["phoneDisplay","Display phone"],["phoneE164","International phone"],["email","Public email"],["bookingUrl","Booking URL"]] },
    { title: "Location and messaging", fields: [["locationLabel","Location label"],["serviceArea","Primary service area"],["availabilityMessage","Availability message"],["footerDescription","Footer description"],["serviceAreaDescription","Service-area description"]] },
    { title: "Social and website", fields: [["websiteUrl","Public website URL"],["instagramUrl","Instagram URL"],["facebookUrl","Facebook URL"],["youtubeUrl","YouTube URL"],["linkedinUrl","LinkedIn URL"]] },
    { title: "Default search metadata", fields: [["defaultSeoTitle","Default SEO title"],["defaultSeoDescription","Default SEO description"]] },
  ] as const;
  return <><div className="grid gap-6 xl:grid-cols-2">{groups.map((group) => <section key={group.title} className="rounded-2xl border border-white/[0.08] bg-[#111] p-6"><h2 className="text-xl font-light text-white">{group.title}</h2><div className="mt-6 space-y-5">{group.fields.map(([key,label]) => <label key={key} className="block text-[0.54rem] font-semibold uppercase tracking-[0.15em] text-white/35">{label}{["footerDescription","serviceAreaDescription","defaultSeoDescription"].includes(key) ? <textarea rows={3} value={settings[key] ?? ""} onChange={(event) => update(key, event.target.value)} className="mt-2 w-full resize-y rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-sm normal-case leading-6 tracking-normal text-white outline-none focus:border-[var(--helios-orange)]" /> : <input value={settings[key] ?? ""} onChange={(event) => update(key, event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-sm normal-case tracking-normal text-white outline-none focus:border-[var(--helios-orange)]" />}</label>)}</div></section>)}</div><div className="sticky bottom-5 mt-6 flex items-center justify-between rounded-2xl border border-white/10 bg-[#161616]/95 p-4 shadow-2xl backdrop-blur-xl"><p role="status" className="text-sm text-white/40">{message || "Changes apply across the public website after saving."}</p><button type="button" onClick={save} disabled={saving} className="rounded-full bg-[var(--helios-orange)] px-6 py-3 text-[0.54rem] font-semibold uppercase tracking-[0.14em] text-black disabled:opacity-40">{saving ? "Saving…" : "Save settings"}</button></div></>;
}
