import type { Metadata } from "next";
import Link from "next/link";
import Footer from "@/app/components/Footer";
import Navbar from "@/app/components/Navbar";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Client Portal", description: "Secure client access and custom booking portals.", robots: { index: false, follow: false } };
export default async function ClientPortalPage({ searchParams }: { searchParams: Promise<{ error?: string | string[] }> }) {
  const portals = await prisma.clientPortal.findMany({ where: { active: true }, orderBy: [{ isDefault: "desc" }, { displayOrder: "asc" }, { name: "asc" }] });
  const errorValue = (await searchParams).error; const error = typeof errorValue === "string" ? errorValue : "";
  return <main className="min-h-screen bg-[#090909] text-white"><Navbar variant="solid" /><section className="relative overflow-hidden border-b border-white/[0.08]"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_82%_15%,rgba(217,107,43,0.17),transparent_34%)]" /><div className="container-shell relative py-20 sm:py-28"><p className="eyebrow text-[var(--helios-orange)]">Delivered work & booking</p><h1 className="mt-7 max-w-5xl font-display text-[clamp(4rem,8vw,8rem)] font-light leading-[0.86] tracking-[-0.06em]">Your work.<br />Your dashboard.</h1><p className="mt-8 max-w-2xl text-base leading-8 text-white/42">Choose the portal associated with your company or location. Your email securely determines whether to open an existing dashboard or create a new client account.</p>{error && <p className="mt-6 max-w-2xl border border-red-300/20 bg-red-300/[0.05] px-4 py-3 text-sm text-red-200/75">{error}</p>}</div></section><section className="container-shell py-20 sm:py-28"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{portals.map((portal, index) => <Link key={portal.id} href={`/client-portal/${portal.slug}`} aria-label={`Open ${portal.name}`} className="group flex min-h-72 flex-col justify-between border border-white/[0.09] bg-white/[0.02] p-7 transition duration-500 hover:-translate-y-1 hover:border-[var(--helios-orange)]/45 hover:bg-white/[0.035] focus-visible:-translate-y-1 focus-visible:border-[var(--helios-orange)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--helios-orange)]/40"><div><p className="text-[0.58rem] font-semibold uppercase tracking-[0.18em] text-[var(--helios-orange)]">{String(index + 1).padStart(2, "0")} {portal.isDefault ? "General access" : "Client group"}</p><h2 className="mt-6 font-display text-4xl font-light leading-none tracking-[-0.035em]">{portal.name}</h2><p className="mt-5 text-sm leading-7 text-white/35">{portal.description || "Secure dashboard access and client booking."}</p></div><div className="mt-8 flex items-center justify-between border-t border-white/[0.08] pt-5"><span className="text-[0.62rem] font-semibold uppercase tracking-[0.18em] text-white/60 transition group-hover:text-[var(--helios-orange)] group-focus-visible:text-[var(--helios-orange)]">Open portal</span><span aria-hidden="true" className="text-[var(--helios-orange)] transition-transform duration-300 group-hover:translate-x-1 group-focus-visible:translate-x-1">→</span></div></Link>)}{!portals.length && <div className="border border-white/[0.08] p-8 text-sm leading-7 text-white/35 md:col-span-2">Client portals are being configured. For immediate access, use the booking or contact links below.</div>}</div></section><Footer /></main>;
}
