"use client";

import { useRef, useState } from "react";
import BlogSeriesAssistant from "./BlogSeriesAssistant";

export type BlogSeriesEditor = {
  id:string; name:string; purpose:string; targetAudience:string; cadence:"WEEKLY"|"BIWEEKLY"|"MONTHLY";
  nextPublishAt:string|null; leadDays:number; generationHour:number; contentPillars:string[]; brandVoice:string;
  prioritizeTopics:string|null; avoidTopics:string|null; targetLength:number; seoFocus:string|null;
  preferredCta:string|null; imagePreferences:string|null; status:"ACTIVE"|"PAUSED"|"ARCHIVED";
};
const defaultPillars=["Real Estate Photography","Cinematic Video","Aerial Media","Listing Marketing","Agent Branding","Social Content","Property Presentation","Behind the Scenes","Helios Updates"];
const blank=():BlogSeriesEditor=>({id:"",name:"",purpose:"",targetAudience:"Real estate agents and property professionals",cadence:"BIWEEKLY",nextPublishAt:new Date(Date.now()+14*86_400_000).toISOString(),leadDays:7,generationHour:8,contentPillars:defaultPillars,brandVoice:"Refined, intentional, cinematic, knowledgeable, useful, and human.",prioritizeTopics:"",avoidTopics:"Unsupported statistics, generic AI filler, repetitive topics, and keyword stuffing.",targetLength:1000,seoFocus:"",preferredCta:"Invite readers to explore the relevant Helios service.",imagePreferences:"Recommend a relevant approved Helios portfolio image.",status:"ACTIVE"});
const input="mt-2 w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-sm text-white outline-none focus:border-[var(--helios-orange)]";

export default function BlogSeriesPanel({initialSeries,onDraftGenerated}:{initialSeries:BlogSeriesEditor[];onDraftGenerated:()=>void}) {
  const [series,setSeries]=useState(initialSeries);const [draft,setDraft]=useState<BlogSeriesEditor>(blank());const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);
  const newSeriesRef=useRef<HTMLButtonElement>(null);
  const patch=<K extends keyof BlogSeriesEditor>(key:K,value:BlogSeriesEditor[K])=>setDraft(current=>({...current,[key]:value}));
  function closeEditor(){setOpen(false);setMessage(null);window.setTimeout(()=>newSeriesRef.current?.focus(),0);}
  function edit(item:BlogSeriesEditor){setDraft(item);setOpen(true);setMessage(null);}
  async function save(){const editing=Boolean(draft.id);setBusy(true);setMessage(editing?"Updating series…":"Creating series…");try{const response=await fetch("/api/admin/blog/series",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||"Series could not be saved.");const saved={...result.series,nextPublishAt:result.series.nextPublishAt||null,contentPillars:Array.isArray(result.series.contentPillars)?result.series.contentPillars:[]};setSeries(current=>editing?current.map(item=>item.id===saved.id?saved:item):[saved,...current]);setDraft(blank());setOpen(false);setMessage(editing?"Series updated.":"Series created.");window.setTimeout(()=>document.getElementById(`blog-series-${saved.id}`)?.focus(),0);}catch(error){setMessage(error instanceof Error?error.message:"Series could not be saved.");}finally{setBusy(false);}}
  async function generate(id:string){setBusy(true);setMessage("AI is preparing the next draft…");try{const response=await fetch("/api/admin/blog/series/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({seriesId:id})});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||"Draft could not be generated.");setMessage("Draft created in Needs Review ✓");onDraftGenerated();}catch(error){setMessage(error instanceof Error?error.message:"Draft could not be generated.");}finally{setBusy(false);}}
  return <section data-blog-series-panel className="rounded-2xl border border-[var(--helios-orange)]/20 bg-[var(--helios-orange)]/[0.025] p-5 sm:p-7">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow text-[var(--helios-orange)]">AI Blog Series</p><h2 className="mt-2 text-2xl font-light text-white">Recurring editorial drafts</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/40">Active series automatically create review-ready drafts on this schedule. Nothing is published without your approval.</p></div><button ref={newSeriesRef} type="button" aria-expanded={open} aria-controls="blog-series-editor" className="admin-btn-secondary" onClick={()=>{setDraft(blank());setOpen(true);setMessage(null);}}>New Series</button></div>
    <div className="mt-5 grid gap-3 lg:grid-cols-3">{series.map(item=><article id={`blog-series-${item.id}`} tabIndex={-1} key={item.id} className="rounded-xl border border-white/[0.08] bg-black/20 p-4 focus:outline-none focus:ring-1 focus:ring-[var(--helios-orange)]"><div className="flex items-center justify-between gap-3"><h3 className="text-sm text-white/75">{item.name}</h3><span className="text-[0.5rem] uppercase tracking-[.13em] text-white/30">{item.status}</span></div><p className="mt-2 text-xs text-white/35">{item.cadence.toLowerCase()} · next draft generation {item.nextPublishAt?new Date(new Date(item.nextPublishAt).getTime()-item.leadDays*86_400_000).toLocaleDateString():"not scheduled"}</p><div className="mt-4 flex flex-wrap gap-2"><button className="admin-btn-secondary" onClick={()=>edit(item)}>Edit Series</button><button disabled={busy||item.status!=="ACTIVE"} className="admin-btn-primary" onClick={()=>generate(item.id)}>Generate Draft Now</button></div></article>)}{!series.length&&<p className="text-sm text-white/30">No recurring series yet. Every two weeks is the recommended starting cadence.</p>}</div>
    {open&&<div id="blog-series-editor" className="mt-6 space-y-5 border-t border-white/10 pt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow text-[var(--helios-orange)]">{draft.id?"Edit Blog Series":"New Blog Series"}</p><h3 className="mt-2 font-serif text-2xl text-white">{draft.id?draft.name||"Series editor":"Build your series"}</h3></div><button type="button" onClick={closeEditor} className="admin-btn-secondary" aria-label="Close Blog Series form">Close Series Form</button></div><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[var(--helios-orange)]/20 bg-[var(--helios-orange)]/[.04] p-4"><div><h3 className="font-serif text-lg text-white">Start with a strategic roadmap</h3><p className="mt-1 text-xs leading-5 text-white/40">Suggestions remain temporary until you apply them and use Save series.</p></div><BlogSeriesAssistant draft={draft} onChange={setDraft}/></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Internal series name"><input className={input} value={draft.name} onChange={e=>patch("name",e.target.value)}/></Field><Field label="Target audience"><input className={input} value={draft.targetAudience} onChange={e=>patch("targetAudience",e.target.value)}/></Field></div><Field label="Purpose"><textarea rows={3} className={input} value={draft.purpose} onChange={e=>patch("purpose",e.target.value)}/></Field>
      <div className="grid gap-5 sm:grid-cols-3"><Field label="Cadence"><select className={input} value={draft.cadence} onChange={e=>patch("cadence",e.target.value as BlogSeriesEditor["cadence"])}><option value="WEEKLY">Weekly</option><option value="BIWEEKLY">Every two weeks (recommended)</option><option value="MONTHLY">Monthly</option></select></Field><Field label="Intended publication"><input type="datetime-local" className={input} value={draft.nextPublishAt?.slice(0,16)||""} onChange={e=>patch("nextPublishAt",e.target.value?new Date(e.target.value).toISOString():null)}/></Field><Field label="Generate days before"><input type="number" min={1} max={30} className={input} value={draft.leadDays} onChange={e=>patch("leadDays",Number(e.target.value))}/></Field></div>
      <Field label="Content pillars — one per line"><textarea rows={5} className={input} value={draft.contentPillars.join("\n")} onChange={e=>patch("contentPillars",e.target.value.split("\n").map(value=>value.trim()).filter(Boolean))}/></Field><Field label="Helios brand voice"><textarea rows={3} className={input} value={draft.brandVoice} onChange={e=>patch("brandVoice",e.target.value)}/></Field>
      <div className="grid gap-5 sm:grid-cols-2"><Field label="Subjects to prioritize"><textarea rows={3} className={input} value={draft.prioritizeTopics||""} onChange={e=>patch("prioritizeTopics",e.target.value)}/></Field><Field label="Subjects to avoid"><textarea rows={3} className={input} value={draft.avoidTopics||""} onChange={e=>patch("avoidTopics",e.target.value)}/></Field><Field label="SEO focus"><input className={input} value={draft.seoFocus||""} onChange={e=>patch("seoFocus",e.target.value)}/></Field><Field label="Target article length"><input type="number" min={500} max={2500} className={input} value={draft.targetLength} onChange={e=>patch("targetLength",Number(e.target.value))}/></Field><Field label="Preferred call to action"><textarea rows={2} className={input} value={draft.preferredCta||""} onChange={e=>patch("preferredCta",e.target.value)}/></Field><Field label="Image preferences"><textarea rows={2} className={input} value={draft.imagePreferences||""} onChange={e=>patch("imagePreferences",e.target.value)}/></Field></div>
      <div className="flex flex-wrap items-end gap-3"><Field label="Series status"><select className={input} value={draft.status} onChange={e=>patch("status",e.target.value as BlogSeriesEditor["status"])}><option value="ACTIVE">Active</option><option value="PAUSED">Paused</option><option value="ARCHIVED">Archived</option></select></Field><button disabled={busy||!draft.name.trim()||!draft.purpose.trim()} onClick={save} className="admin-btn-primary">{busy?"Working…":"Save series"}</button><button type="button" onClick={closeEditor} className="admin-btn-secondary">Close</button></div></div>}
    {message&&<p role="status" className="mt-4 text-sm text-white/55">{message}</p>}
  </section>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs text-white/40">{label}{children}</label>;}
