"use client";

import { useRef, useState } from "react";
import AccessibleDialog from "@/app/admin/newsletter-studio/components/AccessibleDialog";
import type { BlogSeriesProposal, SeriesCadence } from "@/lib/blog-series-assistant";
import type { BlogSeriesEditor } from "./BlogSeriesPanel";

type Brief = { concept:string; audience:string; objective:string; geographicFocus:string; cadence:SeriesCadence; direction:string };
type ApplicableKey = "name"|"targetAudience"|"purpose"|"cadence"|"leadDays"|"contentPillars"|"brandVoice"|"prioritizeTopics"|"avoidTopics"|"seoFocus"|"targetLength"|"preferredCta"|"imagePreferences";
const input="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white outline-none focus:border-[var(--helios-orange)] focus:ring-1 focus:ring-[var(--helios-orange)]";
const initialBrief:Brief={concept:"",audience:"Real estate agents and property professionals",objective:"",geographicFocus:"Northern Colorado",cadence:"BIWEEKLY",direction:""};
const fields:Array<{key:ApplicableKey;proposal:keyof BlogSeriesProposal;label:string}>=[
  {key:"name",proposal:"seriesName",label:"Internal series name"},{key:"targetAudience",proposal:"targetAudience",label:"Target audience"},{key:"purpose",proposal:"purpose",label:"Purpose"},{key:"cadence",proposal:"cadence",label:"Cadence"},{key:"leadDays",proposal:"generateDaysBefore",label:"Generation lead time"},{key:"contentPillars",proposal:"contentPillars",label:"Content pillars"},{key:"brandVoice",proposal:"brandVoice",label:"Brand voice"},{key:"prioritizeTopics",proposal:"subjectsToPrioritize",label:"Subjects to prioritize"},{key:"avoidTopics",proposal:"subjectsToAvoid",label:"Subjects to avoid"},{key:"seoFocus",proposal:"seoFocus",label:"SEO focus"},{key:"targetLength",proposal:"targetArticleLength",label:"Article length"},{key:"preferredCta",proposal:"preferredCallToAction",label:"Preferred call to action"},{key:"imagePreferences",proposal:"imagePreferences",label:"Image preferences"},
];
const shown=(value:unknown)=>Array.isArray(value)?value.join("\n"):String(value??"");
const empty=(value:unknown)=>Array.isArray(value)?value.length===0:value===null||value===undefined||String(value).trim()==="";

export default function BlogSeriesAssistant({draft,onChange}:{draft:BlogSeriesEditor;onChange:(draft:BlogSeriesEditor)=>void}){
  const [open,setOpen]=useState(false),[step,setStep]=useState(0),[brief,setBrief]=useState(initialBrief),[proposal,setProposal]=useState<BlogSeriesProposal|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[replace,setReplace]=useState<ApplicableKey|null>(null);
  const trigger=useRef<HTMLButtonElement>(null);
  const close=()=>{if(!busy)setOpen(false)};
  async function generate(regenerateField=""){
    setBusy(true);setError("");setNotice(regenerateField?`Regenerating ${regenerateField}…`:"Building your series strategy…");
    try{const response=await fetch("/api/admin/blog/series/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brief,currentForm:draft,currentProposal:proposal,regenerateField})});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||"The proposal could not be generated.");setProposal(result.proposal);setStep(regenerateField?step:1);setNotice(regenerateField?`${regenerateField} regenerated for review.`:"Series proposal ready for review.");}catch(cause){setError(cause instanceof Error?cause.message:"The proposal could not be generated.");setNotice("");}finally{setBusy(false)}}
  function valueFor(field:(typeof fields)[number]){return proposal?.[field.proposal] as BlogSeriesEditor[ApplicableKey]}
  function apply(field:(typeof fields)[number],confirmed=false){if(!proposal)return;const current=draft[field.key];if(!empty(current)&&!confirmed){setReplace(field.key);return}onChange({...draft,[field.key]:valueFor(field)});setReplace(null);setNotice(`${field.label} applied to the unsaved form.`)}
  function applyEmpty(){if(!proposal)return;const next={...draft};for(const field of fields)if(empty(next[field.key]))Object.assign(next,{[field.key]:valueFor(field)});onChange(next);setNotice("All empty fields were populated. Existing content was preserved.")}
  function editProposal(field:(typeof fields)[number],value:string){if(!proposal)return;let next:unknown=value;if(field.key==="contentPillars")next=value.split("\n").map(item=>item.trim()).filter(Boolean);if(field.key==="leadDays"||field.key==="targetLength")next=Number(value);setProposal({...proposal,[field.proposal]:next})}
  return <><button ref={trigger} type="button" className="admin-btn-primary" onClick={()=>{setOpen(true);setError("");}}>Build Series with AI</button>
    <AccessibleDialog open={open} onClose={close} labelledBy="blog-series-assistant-title" size="max-w-6xl">
      <div className="border-b border-white/10 p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-[var(--helios-orange)]">Blog Studio</p><h2 id="blog-series-assistant-title" className="mt-2 font-serif text-2xl font-light text-white sm:text-3xl">Blog Series AI Assistant</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/45">Plan a coherent series, review every suggestion, then choose what enters the unsaved form.</p></div><button type="button" disabled={busy} onClick={close} className="admin-btn-secondary">Close</button></div>
        <ol aria-label="Assistant progress" className="mt-6 grid grid-cols-2 gap-2 text-[.65rem] uppercase tracking-[.12em] text-white/35 sm:grid-cols-4">{["Brief","Strategy","Roadmap","Review and Apply"].map((label,index)=><li key={label} aria-current={step===index?"step":undefined} className={`rounded-lg border px-3 py-2 ${step===index?"border-[var(--helios-orange)] text-white":"border-white/10"}`}>{index+1}. {label}</li>)}</ol></div>
      <div className="max-h-[calc(100vh-15rem)] overflow-y-auto p-5 sm:p-7">
        <div className="sr-only" aria-live="polite">{notice}</div>{error&&<p role="alert" className="mb-5 rounded-xl border border-red-300/25 bg-red-300/[.06] p-4 text-sm text-red-100">{error}</p>}
        {step===0&&<div className="grid gap-5 sm:grid-cols-2"><Field label="Series concept"><textarea rows={5} className={input} value={brief.concept} onChange={e=>setBrief({...brief,concept:e.target.value})}/></Field><Field label="Primary audience"><textarea rows={5} className={input} value={brief.audience} onChange={e=>setBrief({...brief,audience:e.target.value})}/></Field><Field label="Business objective"><textarea rows={4} className={input} value={brief.objective} onChange={e=>setBrief({...brief,objective:e.target.value})}/></Field><Field label="Geographic focus (optional)"><input className={input} value={brief.geographicFocus} onChange={e=>setBrief({...brief,geographicFocus:e.target.value})}/></Field><Field label="Desired cadence"><select className={input} value={brief.cadence} onChange={e=>setBrief({...brief,cadence:e.target.value as SeriesCadence})}><option value="WEEKLY">Weekly</option><option value="BIWEEKLY">Every two weeks</option><option value="MONTHLY">Monthly</option></select></Field><Field label="Additional direction (optional)"><textarea rows={4} className={input} value={brief.direction} onChange={e=>setBrief({...brief,direction:e.target.value})}/></Field></div>}
        {step===1&&proposal&&<div className="space-y-4"><p className="text-sm leading-6 text-white/45">Compare each suggestion with the current form. Existing values require an explicit replacement confirmation.</p>{fields.map(field=><article key={field.key} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-xs font-semibold uppercase tracking-[.13em] text-white/55">{field.label}</h3><div className="flex gap-2"><button type="button" disabled={busy} className="admin-btn-secondary" onClick={()=>generate(String(field.proposal))}>Regenerate</button><button type="button" className="admin-btn-primary" onClick={()=>apply(field)}>{empty(draft[field.key])?"Apply":"Review replacement"}</button></div></div><p className="mt-3 text-xs text-white/30">Current: {shown(draft[field.key])||"Empty"}</p><textarea aria-label={`Proposed ${field.label}`} rows={Array.isArray(valueFor(field))?4:2} className={input} value={shown(valueFor(field))} onChange={e=>editProposal(field,e.target.value)}/>{replace===field.key&&<div className="mt-3 rounded-lg border border-amber-300/25 bg-amber-300/[.05] p-3 text-sm text-amber-100"><p>This replaces existing form content. Nothing is saved yet.</p><div className="mt-3 flex gap-2"><button type="button" className="admin-btn-primary" onClick={()=>apply(field,true)}>Replace field</button><button type="button" className="admin-btn-secondary" onClick={()=>setReplace(null)}>Keep current</button></div></div>}</article>)}</div>}
        {step===2&&proposal&&<div className="space-y-4">{proposal.roadmap.map(item=><article key={`${item.publicationOrder}-${item.workingTitle}`} className="rounded-xl border border-white/10 bg-black/20 p-4"><p className="eyebrow text-[var(--helios-orange)]">Article {item.publicationOrder}</p><h3 className="mt-2 font-serif text-xl text-white">{item.workingTitle}</h3><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Detail label="Topic" value={item.primaryTopic}/><Detail label="Search intent" value={item.searchIntent}/><Detail label="Keyword theme" value={[item.primaryKeyword,...item.supportingKeywords].join(", ")}/><Detail label="Angle" value={item.articleAngle}/><Detail label="Reader takeaway" value={item.readerTakeaway}/><Detail label="Service" value={item.relevantService}/><Detail label="Internal links" value={item.internalLinks.join(", ")}/><Detail label="Media category" value={item.mediaCategory}/><Detail label="Call to action" value={item.callToAction}/></dl></article>)}</div>}
        {step===3&&proposal&&<div className="space-y-5"><section className="rounded-xl border border-white/10 p-4"><h3 className="font-serif text-xl text-white">Conflict review</h3>{proposal.conflicts.length?proposal.conflicts.map(item=><div key={`${item.conflictingContent}-${item.revisedTopic}`} className="mt-4 border-t border-white/10 pt-4 text-sm leading-6 text-white/55"><p className="text-white/75">{item.conflictingContent}</p><p>{item.reason}</p><p><span className="text-[var(--helios-orange)]">Differentiate:</span> {item.differentiation}</p><p><span className="text-[var(--helios-orange)]">Revised:</span> {item.revisedTopic}</p></div>):<p className="mt-3 text-sm text-white/40">No likely overlap was identified.</p>}</section>{proposal.factualConfirmations.length>0&&<section className="rounded-xl border border-amber-300/20 bg-amber-300/[.04] p-4"><h3 className="text-sm text-amber-100">Factual confirmation required</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-white/55">{proposal.factualConfirmations.map(item=><li key={item}>{item}</li>)}</ul></section>}<p className="text-sm leading-6 text-white/45">Applying suggestions only changes this unsaved form. It does not create a series or any articles.</p></div>}
      </div>
      <div className="flex flex-col-reverse gap-2 border-t border-white/10 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-7"><button type="button" disabled={busy} onClick={close} className="admin-btn-secondary">Cancel</button><div className="flex flex-wrap justify-end gap-2">{step>0&&<button type="button" disabled={busy} onClick={()=>setStep(step-1)} className="admin-btn-secondary">{step===1?"Return to Brief":"Back"}</button>}{step===0&&<button type="button" disabled={busy||!brief.concept.trim()||!brief.audience.trim()||!brief.objective.trim()} onClick={()=>generate()} className="admin-btn-primary">{busy?"Building strategy…":"Build proposal"}</button>}{step===1&&proposal&&<><button type="button" onClick={applyEmpty} className="admin-btn-secondary">Apply All Empty Fields</button><button type="button" onClick={()=>setStep(2)} className="admin-btn-primary">Review roadmap</button></>}{step===2&&<button type="button" onClick={()=>setStep(3)} className="admin-btn-primary">Review conflicts</button>}{step===3&&<button type="button" onClick={close} className="admin-btn-primary">Return to unsaved form</button>}</div></div>
    </AccessibleDialog></>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs text-white/45">{label}{children}</label>}
function Detail({label,value}:{label:string;value:string}){return <div><dt className="text-[.65rem] uppercase tracking-[.12em] text-white/30">{label}</dt><dd className="mt-1 leading-6 text-white/60">{value}</dd></div>}
