"use client";
import { useEffect, useRef, useState } from "react";
const fieldControl = "mt-2 h-16 w-full rounded-xl border border-white/10 bg-black/25 px-5 text-base text-white outline-none transition focus:border-[var(--helios-orange)] focus:ring-1 focus:ring-[var(--helios-orange)]";
const selectControl = `${fieldControl} cursor-pointer appearance-none pr-12`;
const messageControl = "mt-2 min-h-48 w-full resize-y rounded-xl border border-white/10 bg-black/25 px-5 py-4 text-base leading-7 text-white outline-none transition focus:border-[var(--helios-orange)] focus:ring-1 focus:ring-[var(--helios-orange)]";
export default function ContactForm() {
  const renderedAt = useRef(0); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [complete, setComplete] = useState(false);
  useEffect(() => { renderedAt.current = Date.now(); }, []);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); const form = new FormData(event.currentTarget); const reason = String(form.get("reason") || "General question"); const preferredContact = String(form.get("preferredContact") || "Email"); const message = String(form.get("message") || ""); try { const response = await fetch("/api/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), email: form.get("email"), phone: form.get("phone"), message: `Reason: ${reason}\nPreferred contact: ${preferredContact}\n\n${message}`, consent: form.get("consent") === "on", website: form.get("website"), renderedAt: renderedAt.current, serviceIds: [], sourcePage: window.location.pathname, referrer: document.referrer || null, ctaName: "General Contact" }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || "Your message could not be sent."); setComplete(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "Your message could not be sent."); } finally { setBusy(false); } }
  if (complete) return <div className="flex min-h-[34rem] flex-col items-center justify-center rounded-2xl border border-emerald-300/15 bg-emerald-300/[0.035] p-10 text-center"><div className="flex h-14 w-14 items-center justify-center rounded-full border border-emerald-300/20 text-2xl text-emerald-200">✓</div><h2 className="mt-7 font-display text-4xl font-light">Message received.</h2><p className="mt-4 max-w-md text-sm leading-7 text-white/40">Thank you for reaching out. The Helios team will respond using your preferred contact method.</p></div>;
  return <form onSubmit={submit} className="rounded-2xl border border-white/[0.1] bg-[#111]/90 p-6 shadow-2xl backdrop-blur-xl sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><Field label="Name"><input name="name" required maxLength={120} autoComplete="name" className={fieldControl} /></Field><Field label="Email"><input name="email" required type="email" maxLength={320} autoComplete="email" className={fieldControl} /></Field><Field label="Phone (optional)"><input name="phone" maxLength={40} autoComplete="tel" className={fieldControl} /></Field><Field label="Reason for contacting"><div className="relative"><select name="reason" className={selectControl}><option>General question</option><option>Existing project support</option><option>Billing</option><option>Partnership</option><option>Other</option></select><SelectChevron /></div></Field><Field label="Preferred contact method"><div className="relative"><select name="preferredContact" className={selectControl}><option>Email</option><option>Phone call</option><option>Text message</option></select><SelectChevron /></div></Field><div className="sm:col-span-2"><Field label="Message"><textarea name="message" required maxLength={2600} rows={7} className={messageControl} /></Field></div></div><input name="website" tabIndex={-1} autoComplete="off" className="sr-only" aria-hidden="true" /><label className="mt-6 flex items-start gap-3 text-xs leading-5 text-white/35"><input name="consent" required type="checkbox" className="mt-0.5 accent-[var(--helios-orange)]" />I agree that Helios may contact me about this message.</label>{error && <p role="alert" className="mt-5 rounded-xl border border-red-400/20 bg-red-400/[0.06] px-4 py-3 text-sm text-red-200/80">{error}</p>}<button type="submit" disabled={busy} className="mt-7 flex min-h-14 w-full items-center justify-center rounded-xl bg-[var(--helios-orange)] px-6 text-[0.6rem] font-semibold uppercase tracking-[0.18em] text-black transition hover:bg-[var(--helios-orange-hover)] disabled:opacity-50">{busy ? "Sending message…" : "Send message"}</button></form>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-[0.55rem] font-semibold uppercase tracking-[0.16em] text-white/35">{label}{children}</label>; }
function SelectChevron() { return <svg aria-hidden="true" viewBox="0 0 12 8" className="pointer-events-none absolute right-5 top-1/2 h-2 w-3 -translate-y-1/2 text-white/45"><path d="m1 1 5 5 5-5" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" /></svg>; }
