-- AlterTable
ALTER TABLE "TrustedLogo"
ADD COLUMN "monochrome" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "displayColor" TEXT NOT NULL DEFAULT '#D8D3CC',
ADD COLUMN "displayOpacity" DOUBLE PRECISION NOT NULL DEFAULT 0.68,
ADD COLUMN "displayScale" DOUBLE PRECISION NOT NULL DEFAULT 1;
