ALTER TABLE "SiteSettings"
  ADD COLUMN "heroPosterAlt" TEXT DEFAULT 'Luxury real estate exterior photographed by Helios Real Estate Media',
  ADD COLUMN "heroEyebrow" TEXT DEFAULT 'Fort Collins, Colorado',
  ADD COLUMN "heroHeadlineLineOne" TEXT DEFAULT 'Luxury Marketing',
  ADD COLUMN "heroHeadlineLineTwo" TEXT DEFAULT 'for Exceptional Homes',
  ADD COLUMN "heroBody" TEXT DEFAULT 'Photography, cinematic films, aerial imagery, and branding crafted to elevate Northern Colorado''s most exceptional homes.',
  ADD COLUMN "heroPrimaryLabel" TEXT DEFAULT 'Book Now',
  ADD COLUMN "heroPrimaryDestination" TEXT,
  ADD COLUMN "heroSecondaryLabel" TEXT DEFAULT 'View Portfolio',
  ADD COLUMN "heroSecondaryDestination" TEXT DEFAULT '/portfolio',
  ADD COLUMN "availabilityEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "availabilityLabel" TEXT DEFAULT 'Now booking',
  ADD COLUMN "standardEyebrow" TEXT DEFAULT 'The Helios Standard',
  ADD COLUMN "standardHeadingLineOne" TEXT DEFAULT 'Media with',
  ADD COLUMN "standardHeadingLineTwo" TEXT DEFAULT 'Measured Intention',
  ADD COLUMN "standardBody" TEXT DEFAULT 'Every frame is composed with purpose—guiding attention, creating emotion, and revealing what makes the property exceptional.',
  ADD COLUMN "workEyebrow" TEXT DEFAULT 'Our Work',
  ADD COLUMN "workHeadingLineOne" TEXT DEFAULT 'Crafted to',
  ADD COLUMN "workHeadingLineTwo" TEXT DEFAULT 'Capture',
  ADD COLUMN "workHeadingAccent" TEXT DEFAULT 'Attention.',
  ADD COLUMN "workBody" TEXT DEFAULT 'Every image, every frame, and every film is crafted to elevate perception, command attention, and inspire confidence before the first showing.',
  ADD COLUMN "workButtonLabel" TEXT DEFAULT 'Explore Portfolio',
  ADD COLUMN "workButtonDestination" TEXT DEFAULT '/portfolio',
  ADD COLUMN "featuredProjectEyebrow" TEXT DEFAULT 'Featured Project',
  ADD COLUMN "portfolioEyebrow" TEXT DEFAULT 'Complete Portfolio',
  ADD COLUMN "portfolioHeading" TEXT DEFAULT 'Explore the Full Collection.',
  ADD COLUMN "portfolioButtonLabel" TEXT DEFAULT 'View Complete Portfolio',
  ADD COLUMN "portfolioButtonDestination" TEXT DEFAULT '/portfolio',
  ADD COLUMN "approachEyebrow" TEXT DEFAULT 'Our Approach',
  ADD COLUMN "approachHeadingLineOne" TEXT DEFAULT 'We Build',
  ADD COLUMN "approachHeadingLineTwo" TEXT DEFAULT 'Perceived Value.',
  ADD COLUMN "approachBody" TEXT DEFAULT 'Every listing is treated like a campaign. Every image, frame, and film is shaped to capture attention, create emotion, and elevate the way a property is perceived.',
  ADD COLUMN "conversionImageCaption" TEXT DEFAULT 'Presentation shapes perception.';
