import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { deterministicBrief, safeSummary } from "@/lib/social/analytics-core";
export const dynamic="force-dynamic";
export default async function MonthlyReport({searchParams}:{searchParams:Promise<{month?:string}>}){
 const query=await searchParams;const parsed=/^\d{4}-\d{2}$/.test(query.month||"")?query.month!:new Date().toISOString().slice(0,7);const [year,month]=parsed.split("-").map(Number);const start=new Date(Date.UTC(year,month-1,1));const end=new Date(Date.UTC(year,month,1));
 const [posts,metrics]=await Promise.all([prisma.socialVariant.findMany({where:{status:"PUBLISHED",publishedAt:{gte:start,lt:end}},include:{campaign:{select:{internalName:true}},metricSnapshots:{where:{measuredAt:{gte:start,lt:end}},orderBy:{measuredAt:"desc"},take:50}},orderBy:{publishedAt:"desc"}}),prisma.socialMetricSnapshot.findMany({where:{measuredAt:{gte:start,lt:end}},orderBy:{measuredAt:"desc"},take:3000})]);
 const summary=safeSummary(metrics.map(item=>({platform:item.platform,variantId:item.variantId,category:item.normalizedCategory,providerName:item.providerMetricName,value:item.value===null?null:Number(item.value),availability:item.availability,measuredAt:item.measuredAt})));const briefing=deterministicBrief({published:posts.length,metrics:summary,sampleSize:posts.length,stale:false});
 return <div className="space-y-8 pb-12 print:bg-white print:text-black"><section className="border-b border-white/10 pb-7"><p className="eyebrow text-[var(--helios-orange)]">Monthly social report</p><h1 className="mt-3 text-4xl font-light text-white">{start.toLocaleDateString("en-US",{month:"long",year:"numeric",timeZone:"UTC"})}</h1><p className="mt-3 text-sm text-white/40">Verified official-platform data with explicit availability notes.</p></section><section className="rounded-2xl border border-white/10 p-6"><h2 className="text-xl text-white/80">Executive summary</h2><p className="mt-3 text-sm leading-7 text-white/55">{briefing}</p></section><section className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["Posts",posts.length],["Reach",summary.reach],["Impressions",summary.impressions],["Supported engagement",summary.engagements]].map(([label,value])=><div key={String(label)} className="rounded-xl border border-white/10 p-5"><p className="text-xs uppercase text-white/30">{label}</p><p className="mt-3 text-3xl text-white/75">{value===null?"Not Available":Number(value).toLocaleString()}</p></div>)}</section><section className="rounded-2xl border border-white/10 p-6"><h2 className="text-xl text-white/80">Publishing activity</h2><div className="mt-4 space-y-3">{posts.map(post=><div key={post.id} className="flex justify-between border-t border-white/[.06] pt-3 text-sm"><span className="text-white/60">{post.campaign.internalName} · {post.platform}</span><span className="text-white/30">{post.publishedAt?.toLocaleDateString()}</span></div>)}{!posts.length&&<p className="text-white/35">No posts were published during this month.</p>}</div></section><section className="rounded-2xl border border-white/10 p-6 text-xs leading-6 text-white/35"><h2 className="text-base text-white/70">Data notes</h2><p className="mt-2">Cross-platform reach is not presented as unique people. Provider-calculated rates and incompatible video-view definitions are not combined. Missing metrics remain unavailable rather than zero.</p></section><div className="flex gap-2 print:hidden"><Link href="/admin/social-studio/analytics" className="admin-btn-secondary">Back to analytics</Link><button onClick={undefined} className="admin-btn-secondary" aria-label="Use browser print command">Print-friendly view</button></div></div>;
}
