"use client";

import Link from "next/link";
import { useState } from "react";

type Settings = { brandVoice: string; primaryAudience: string; writingGuardrails: string; defaultCallToAction: string; hashtagGuidance: string; prohibitedTopics: string; platformGuidance: Record<string, string> };
type Connection = { id:string; platform: string; state: string; intendedAccountName: string; providerUsername:string; supportedWorkflow: string; manualPublishingUrl: string; directPublishingEnabled:boolean; configured:boolean; missing:string[] };
export default function SocialSettings({ initialSettings, initialConnections }: { initialSettings: Settings; initialConnections: Connection[] }) {
  const [settings, setSettings] = useState(initialSettings); const [connections, setConnections] = useState(initialConnections); const [expanded, setExpanded] = useState(false); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function saveSettings() { setSaving(true); const response = await fetch("/api/admin/social/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); setSaving(false); setMessage(response.ok ? "Social Studio Voice saved." : "Settings could not be saved."); }
  async function saveConnection(connection: Connection) { setSaving(true); const response = await fetch("/api/admin/social/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "connection", ...connection }) }); setSaving(false); setMessage(response.ok ? `${connection.platform} configuration saved.` : "Connection configuration could not be saved."); }
  async function connectionAction(connection:Connection,action:string){setSaving(true);const response=await fetch("/api/admin/social/connections",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({connectionId:connection.id,action})});const data=await response.json();setSaving(false);if(response.ok&&data.success){setConnections(all=>all.map(item=>item.id===connection.id?{...item,state:data.state,directPublishingEnabled:data.directPublishingEnabled}:item));setMessage(data.message);}else setMessage(data.error||"Connection action failed.");}
  const input = "mt-2 w-full rounded-xl border border-white/10 bg-black/25 p-4 text-sm font-normal normal-case leading-6 tracking-normal text-white outline-none focus:border-[var(--helios-orange)]";
  const fields: Array<[keyof Omit<Settings,"platformGuidance">, string]> = [["brandVoice","Brand Voice"],["primaryAudience","Primary Audience"],["writingGuardrails","Writing Guardrails"],["defaultCallToAction","Default Call to Action"],["hashtagGuidance","Preferred Hashtag Guidance"],["prohibitedTopics","Prohibited Topics or Claims"]];
  return <div className="space-y-7 pb-10"><section className="flex justify-between gap-4 border-b border-white/[.08] pb-7"><div><Link href="/admin/social-studio" className="text-xs text-white/35">← Social Studio</Link><p className="eyebrow mt-5 text-[var(--helios-orange)]">Configuration</p><h1 className="mt-3 text-3xl font-light text-white sm:text-4xl">Voice & connections</h1></div><button onClick={() => setExpanded(true)} className="admin-btn-secondary self-end">Expand editor</button></section>
  <section className="rounded-2xl border border-white/[.08] bg-white/[.02] p-6"><h2 className="text-2xl font-light text-white">Social Studio Voice</h2><p className="mt-2 text-sm text-white/35">These editable instructions guide every platform draft.</p><div className="mt-6 grid gap-5 lg:grid-cols-2">{fields.map(([key, label]) => <label key={key} className="text-xs uppercase tracking-[.14em] text-white/35">{label}<textarea rows={6} className={input} value={settings[key]} onChange={(e) => setSettings({ ...settings, [key]: e.target.value })}/></label>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2">{Object.entries(settings.platformGuidance).map(([platform, guidance]) => <label key={platform} className="text-xs uppercase tracking-[.14em] text-white/35">{platform} guidance<textarea rows={4} className={input} value={guidance} onChange={(e) => setSettings({ ...settings, platformGuidance: { ...settings.platformGuidance, [platform]: e.target.value } })}/></label>)}</div><button disabled={saving} onClick={saveSettings} className="admin-btn-primary mt-6">{saving ? "Saving…" : "Save Voice"}</button></section>
  <section><p className="eyebrow text-[var(--helios-orange)]">Official API readiness</p><h2 className="mt-2 text-2xl font-light text-white">Social connections</h2><p className="mt-2 text-sm text-white/35">OAuth uses official provider authorization. Connecting never enables publishing; that requires a separate confirmed action.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{connections.map((connection) => {const provider=["INSTAGRAM","FACEBOOK"].includes(connection.platform)?"meta":connection.platform.toLowerCase();return <article key={connection.id} className="rounded-2xl border border-white/[.08] bg-white/[.02] p-5"><div className="flex items-center justify-between gap-3"><h3 className="text-lg text-white/70">{connection.platform}</h3><span className="rounded-full border border-white/10 px-3 py-1 text-[.58rem] uppercase text-white/35">{connection.state.replaceAll("_", " ")}</span></div><label className="mt-4 block text-xs text-white/35">Intended account<input className={input} value={connection.intendedAccountName} onChange={(e) => setConnections((all) => all.map((item) => item.id === connection.id ? { ...item, intendedAccountName: e.target.value } : item))}/></label><label className="mt-4 block text-xs text-white/35">Manual publishing link<input className={input} value={connection.manualPublishingUrl} onChange={(e) => setConnections((all) => all.map((item) => item.id === connection.id ? { ...item, manualPublishingUrl: e.target.value } : item))}/></label><p className="mt-3 text-xs text-white/25">{connection.supportedWorkflow}</p>{!connection.configured&&<p className="mt-3 text-xs text-amber-100/60">Required server configuration: {connection.missing.join(", ")}</p>}<p className="mt-3 text-xs text-white/35">Direct publishing: {connection.directPublishingEnabled?"Enabled":"Disabled"}</p><div className="mt-4 flex flex-wrap gap-2"><button disabled={saving} onClick={() => saveConnection(connection)} className="admin-btn-secondary">Save</button>{connection.configured&& !connection.state.startsWith("CONNECTED")&&<a href={`/api/admin/social/oauth/${provider}/connect`} className="admin-btn-secondary">Connect securely</a>}{connection.state.startsWith("CONNECTED")&&<button disabled={saving} onClick={()=>connectionAction(connection,connection.directPublishingEnabled?"disable":"enable")} className={connection.directPublishingEnabled?"admin-btn-secondary":"admin-btn-primary"}>{connection.directPublishingEnabled?"Disable direct publishing":"Enable direct publishing"}</button>}{connection.state.startsWith("CONNECTED")&&<button disabled={saving} onClick={()=>connectionAction(connection,"disconnect")} className="admin-btn-secondary">Disconnect</button>}</div></article>})}</div></section>
  {message && <p role="status" aria-live="polite" className="text-sm text-white/50">{message}</p>}
  {expanded && <div role="dialog" aria-modal="true" aria-labelledby="social-voice-title" className="fixed inset-0 z-[100] overflow-y-auto bg-black/90 p-4"><div className="mx-auto my-4 max-w-6xl rounded-2xl border border-white/10 bg-[#111] p-6 sm:p-8"><div className="flex justify-between"><h2 id="social-voice-title" className="text-3xl font-light text-white">Social Studio Voice Editor</h2><button onClick={() => setExpanded(false)} className="admin-btn-secondary">Close</button></div><div className="mt-7 grid gap-5">{fields.map(([key, label]) => <label key={key} className="text-xs uppercase tracking-[.14em] text-white/35">{label}<textarea rows={8} className={input} value={settings[key]} onChange={(e) => setSettings({ ...settings, [key]: e.target.value })}/></label>)}</div><div className="mt-7 flex justify-end gap-3"><button onClick={() => setExpanded(false)} className="admin-btn-secondary">Keep editing later</button><button onClick={async () => { await saveSettings(); setExpanded(false); }} className="admin-btn-primary">Save Settings</button></div></div></div>}</div>;
}
