import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { runInNewContext } from 'node:vm';
import test from 'node:test';
import ts from 'typescript';
/* eslint-disable @typescript-eslint/no-explicit-any -- Execute the actual organizer with isolated hooks and transport. */
const ids=['homepage-navigation','homepage-media','featured-project','our-work','homepage-structure'];
const initial={order:ids,collapsed:['homepage-navigation']};
const jsx=(type:any,props:any)=>({type,props});
function elements(n:any):any[]{if(Array.isArray(n))return n.flatMap(elements);if(!n?.props)return [];if(typeof n.type==='function')return elements(n.type(n.props));return [n,...elements(n.props.children)];}
function fixture(fetcher:any,extra:any={}){
 const values:any[]=[];let cursor=0;let workspaceId="a";const cleanups:any[]=[];
 const modules:any={react:{useState(x:any){const i=cursor++;if(!(i in values))values[i]=typeof x==='function'?x():x;return[values[i],(x:any)=>values[i]=typeof x==='function'?x(values[i]):x];},useRef(x:any){const i=cursor++;return values[i]??(values[i]={current:x});},useMemo(fn:any){return fn();},useEffect(fn:any,deps:any[]){const i=cursor++;if(!(i in values)||deps.some((v,n)=>v!==values[i].deps[n])){values[i]?.cleanup?.();const cleanup=fn();values[i]={deps,cleanup};if(cleanup)cleanups.push(cleanup);}},useSyncExternalStore(_s:any,r:any){return r();}},'react/jsx-runtime':{jsx,jsxs:jsx},'@/app/admin/components/AdminSectionNavigator':{default:({actions}:any)=>actions},'@/app/admin/components/AdminCardControls':{AdminDragHandle:()=>null,AdminCardIconButton:({label,onClick,disabled}:any)=>jsx('button',{children:label,onClick,disabled}),AdminCardToggle:()=>null}};
 modules.react.useLayoutEffect=modules.react.useEffect;
 function load(path:string):any{const exports={};runInNewContext(ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,console,AbortController,crypto:globalThis.crypto,setTimeout:()=>0,clearTimeout,fetch:fetcher,window:{location:{hash:'',reload(){}},clearTimeout(){},addEventListener(){},removeEventListener(){}},...extra,require(id:string){if(id in modules)return modules[id];const path=id.startsWith('@/')?id.slice(2):'app/admin/homepage/'+id.slice(2);return modules[id]=load(path+(/\.tsx?$/.test(path)?'':path.includes('use')?'.tsx':'.ts'));}});return exports;}
 const Component=load('app/admin/homepage/HomepageCurationOrganizer.tsx').default;
 const render=()=>{cursor=0;return elements(Component({initialPreferences:initial,initialRevision:'a'.repeat(64),workspaceId,userId:'u',sections:ids.map(id=>({id,title:id,description:id,content:null}))}));};
 return{render,switchWorkspace:(id:string)=>{workspaceId=id;render();},button:(name:string)=>render().find(e=>e.type==='button'&&e.props.children===name),order:()=>render().filter(e=>e.type==='section'&&ids.includes(e.props.id)).map(e=>e.props.id),unmount:()=>cleanups.forEach(f=>f())};
}
const tick=()=>new Promise(r=>setTimeout(r,0));
test('private layout synchronously admits one operation',()=>{let calls=0;const f=fixture(()=>{calls++;return new Promise(()=>{});});const b=f.button('Move homepage-navigation down');b.props.onClick();b.props.onClick();assert.equal(calls,1);});
test('private layout retains attempted order after network uncertainty',async()=>{const f=fixture(async()=>{throw Error('lost');});f.button('Move homepage-navigation down').props.onClick();await tick();assert.equal(f.order()[0],'homepage-media');});
test('private layout rejects unvalidated success without installing foreign order',async()=>{const f=fixture(async()=>Response.json({success:true,preferences:initial}));f.button('Move homepage-navigation down').props.onClick();await tick();assert.equal(f.order()[0],'homepage-media');assert.ok(f.render().some(e=>e.type==='textarea'));});
function response(options:any,mutate?:(r:any)=>void){const r={success:true,preferences:JSON.parse(options.body),acknowledgement:{protocol:1,scope:'private-homepage-layout',intent:'replace',userId:'u',workspaceId:'a',requestId:options.headers['x-layout-request'],previousRevision:options.headers['x-layout-revision'],revision:options.headers['x-layout-revision']==='b'.repeat(64)?'c'.repeat(64):'b'.repeat(64)}};mutate?.(r);return Response.json(r);}
for(const kind of ['workspace','user','revision','previous','request','scope','intent','preferences','json','conflict'])test(`private layout holds ${kind} acknowledgement without replay`,async()=>{let calls=0;const f=fixture(async(_u:any,o:any)=>{calls++;if(kind==='json')return{ok:true,json:async()=>{throw Error('json');}};if(kind==='conflict')return Response.json({success:false},{status:409});return response(o,r=>{const a=r.acknowledgement;if(kind==='workspace')a.workspaceId='b';if(kind==='user')a.userId='other';if(kind==='revision')a.revision=a.previousRevision;if(kind==='previous')a.previousRevision='wrong';if(kind==='request')a.requestId='old';if(kind==='scope')a.scope='public';if(kind==='intent')a.intent='reset';if(kind==='preferences')r.preferences=initial;});});f.button('Move homepage-navigation down').props.onClick();await tick();assert.ok(f.render().some(e=>e.type==='textarea'));assert.equal(f.order()[0],'homepage-media');f.button('Move homepage-media down').props.onClick();await tick();assert.equal(calls,1);});
test('private layout freezes requests, blocks edits during save and advances revision',async()=>{const requests:any[]=[];let finish:any;const f=fixture((_u:any,o:any)=>{requests.push(o);return new Promise(r=>{finish=()=>r(response(o));});});const old=f.button('Move homepage-navigation down');old.props.onClick();f.button('Move homepage-media down').props.onClick();assert.equal(requests.length,1);finish();await tick();old.props.onClick();assert.equal(requests.length,1);f.button('Move homepage-navigation down').props.onClick();assert.equal(requests[1].headers['x-layout-revision'],'b'.repeat(64));assert.equal(JSON.parse(requests[0].body).order[0],'homepage-media');finish();await tick();assert.match(String(f.render().find(e=>e.props.role==='status').props.children),/Confirmed saved/);});
test('private layout timeout preserves choice and fences late success',async()=>{let expire:any,finish:any;const f=fixture((_u:any,o:any)=>new Promise(r=>{finish=()=>r(response(o));}),{setTimeout:(fn:any)=>{expire=fn;return 1;}});f.button('Move homepage-navigation down').props.onClick();expire();await tick();assert.ok(f.render().some(e=>e.type==='textarea'));finish();await tick();assert.equal(f.order()[0],'homepage-media');assert.match(String(f.render().find(e=>e.props.role==='status').props.children),/uncertain/);});
test('private layout unmount fences late callback',async()=>{let finish:any;const f=fixture((_u:any,o:any)=>new Promise(r=>{finish=()=>r(response(o));}));f.button('Move homepage-navigation down').props.onClick();f.unmount();finish();await tick();assert.doesNotMatch(String(f.render().find(e=>e.props.role==='status').props.children),/Confirmed/);});
test('private layout reload requires retained copy and never retries',async()=>{let reloads=0,calls=0;const f=fixture(async()=>{calls++;throw Error('lost');},{window:{location:{hash:'',reload(){reloads++;}},clearTimeout(){},addEventListener(){},removeEventListener(){}}});f.button('Move homepage-navigation down').props.onClick();await tick();assert.equal(f.button('Reload to reconcile').props.disabled,true);f.render().find(e=>e.props.type==='checkbox').props.onChange({target:{checked:true}});f.button('Reload to reconcile').props.onClick();assert.equal(reloads,1);assert.equal(calls,1);});

test('private layout fences previous workspace callbacks before and after a context switch',async()=>{let finish:any,calls=0;const f=fixture((_u:any,o:any)=>{calls++;return new Promise(r=>{finish=()=>r(response(o));});});const old=f.button('Move homepage-navigation down');old.props.onClick();f.switchWorkspace('b');finish();await tick();old.props.onClick();assert.equal(calls,1);assert.doesNotMatch(String(f.render().find(e=>e.props.role==='status').props.children),/Confirmed/);});
test('private layout JSON timeout fences settlement after an unknown outcome',async()=>{let expire:any,settle:any;const f=fixture(async(_u:any,o:any)=>({ok:true,status:200,json:()=>new Promise(r=>{settle=async()=>r(await response(o).json());})}),{setTimeout:(fn:any)=>{expire=fn;return 1;}});f.button('Move homepage-navigation down').props.onClick();await tick();expire();await tick();settle();await tick();assert.match(String(f.render().find(e=>e.props.role==='status').props.children),/uncertain/);assert.equal(f.order()[0],'homepage-media');});

test('private layout older-server response after a confirmed new save holds the next choice without replay',async()=>{
 let calls=0;const f=fixture(async(_u:any,o:any)=>{calls++;return calls===1?response(o):Response.json({success:true,preferences:JSON.parse(o.body)});});
 f.button('Move homepage-navigation down').props.onClick();await tick();
 assert.match(String(f.render().find(e=>e.props.role==='status').props.children),/Confirmed saved/);
 f.button('Move homepage-navigation down').props.onClick();await tick();assert.equal(f.order()[2],'homepage-navigation');assert.ok(f.render().some(e=>e.type==='textarea'));
 f.button('Move homepage-navigation down').props.onClick();await tick();assert.equal(calls,2);
});
