import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
import {createHash,randomUUID} from 'node:crypto';
import test from 'node:test';
import ts from 'typescript';
import {PGlite} from '@electric-sql/pglite';
/* eslint-disable @typescript-eslint/no-explicit-any -- Real route and SQL in isolated PGlite delegates, not Prisma contention. */
const prefs={order:['homepage-navigation','homepage-media','featured-project','our-work','homepage-structure'],collapsed:['homepage-navigation']};
async function fixture(){
 const db=new PGlite();await db.exec(`CREATE TABLE "Workspace" (id text primary key); CREATE TABLE "AdminUser" (id text primary key,"workspaceId" text,active boolean,role text,"sessionVersion" int,"homepageCurationPreferences" jsonb); CREATE TABLE "WorkspaceMembership" (id text,"userId" text,"workspaceId" text,status text,role text);INSERT INTO "Workspace" VALUES ('a'),('b');INSERT INTO "AdminUser" VALUES ('u','a',true,'VIEWER',1,null);INSERT INTO "WorkspaceMembership" VALUES ('m','u','a','ACTIVE','VIEWER');`);
 let zero=false,badRead=false,writes=0;
 const delegate=(sql:any)=>({$queryRaw:(strings:TemplateStringsArray,...args:any[])=>sql.query(strings.reduce((q,s,i)=>q+(i?'$'+i:'')+s,''),args).then((r:any)=>r.rows),adminUser:{findFirst:async({where}:any)=>{const row=(await sql.query('SELECT * FROM "AdminUser" WHERE id=$1 AND "workspaceId"=$2',[where.id,where.workspaceId])).rows[0]??null;return badRead&&writes?null:row;},updateMany:async({where,data}:any)=>{if(zero)return{count:0};writes++;return{count:(await sql.query('UPDATE "AdminUser" SET "homepageCurationPreferences"=$1::jsonb WHERE id=$2 AND "workspaceId"=$3 AND active=true AND "sessionVersion"=$4 RETURNING id',[JSON.stringify(data.homepageCurationPreferences),where.id,where.workspaceId,where.sessionVersion])).rows.length};}},workspaceMembership:{findUnique:async()=> (await sql.query('SELECT * FROM "WorkspaceMembership"')).rows[0]}});
 const modules:any={'node:crypto':{createHash,randomUUID},'next/server':{NextResponse:Response},'@/lib/auth/session':{getAdminSession:async()=>({userId:'u',workspaceId:'a',sessionVersion:1})},'@/lib/workspace-context-core':{tenantContextEnabled:()=>true},'@/lib/prisma':{prisma:{$transaction:(fn:any)=>db.transaction(tx=>fn(delegate(tx)))}}};
 const load=(path:string):any=>{const exports={};runInNewContext(ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,console,require(id:string){return modules[id]??(modules[id]=load(id.slice(2)+'.ts'));}});return exports;};
 const route=load('app/api/admin/homepage-layout/route.ts');const revision=load('lib/homepage-layout-revision.ts').homepageLayoutRevision;
 return{db,close:()=>db.close(),zero:()=>{zero=true;},badRead:()=>{badRead=true;},read:async()=> (await db.query<{homepageCurationPreferences:unknown}>('SELECT "homepageCurationPreferences" FROM "AdminUser"')).rows[0].homepageCurationPreferences,initial:revision('u','a',null),write:(rev:string,body:any=prefs,workspace='a')=>route.PATCH(new Request('http://localhost/api',{method:'PATCH',headers:{'x-layout-revision':rev,'x-layout-request':'operation','x-layout-workspace':workspace},body:JSON.stringify(body)}))};
}
test('private layout rejects stale open revision',async()=>{const f=await fixture();try{assert.equal((await f.write('stale')).status,409);assert.equal(await f.read(),null);}finally{await f.close();}});
test('private layout commits authoritative readback and advances even identical choices',async()=>{const f=await fixture();try{const first=await(await f.write(f.initial)).json();assert.equal(first.success,true);assert.deepEqual(first.preferences,prefs);assert.equal(first.acknowledgement.userId,'u');assert.equal(first.acknowledgement.workspaceId,'a');assert.notEqual(first.acknowledgement.revision,f.initial);assert.equal((await f.write(f.initial)).status,409);const second=await(await f.write(first.acknowledgement.revision)).json();assert.notEqual(second.acknowledgement.revision,first.acknowledgement.revision);}finally{await f.close();}});
for(const kind of ['workspace','revoked','inactive','session','zero','readback','null'])test(`private layout fails closed for ${kind}`,async()=>{const f=await fixture();try{
 if(kind==='workspace')await f.db.exec(`UPDATE "AdminUser" SET "workspaceId"='b'`);if(kind==='null')await f.db.exec(`UPDATE "AdminUser" SET "workspaceId"=null`);if(kind==='revoked')await f.db.exec(`UPDATE "WorkspaceMembership" SET status='REVOKED'`);if(kind==='inactive')await f.db.exec(`UPDATE "AdminUser" SET active=false`);if(kind==='session')await f.db.exec(`UPDATE "AdminUser" SET "sessionVersion"=2`);if(kind==='zero')f.zero();if(kind==='readback')f.badRead();assert.equal((await f.write(f.initial)).status,409);assert.equal(await f.read(),null);
 }finally{await f.close();}});
for(const kind of ['missing','duplicate','unknown','collapsed','workspace'])test(`private layout rejects ${kind} submitted context/collection`,async()=>{const f=await fixture();try{const body=structuredClone(prefs);if(kind==='missing')body.order.pop();if(kind==='duplicate')body.order[1]=body.order[0];if(kind==='unknown')body.order[1]='foreign';if(kind==='collapsed')body.collapsed=['foreign'];assert.equal((await f.write(f.initial,body,kind==='workspace'?'b':'a')).status,kind==='workspace'?409:400);assert.equal(await f.read(),null);}finally{await f.close();}});
