CREATE TABLE "LocationPage" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "city" TEXT NOT NULL,
  "state" TEXT NOT NULL DEFAULT 'Colorado',
  "county" TEXT NOT NULL,
  "seoTitle" TEXT NOT NULL,
  "seoDescription" TEXT NOT NULL,
  "heroLead" TEXT NOT NULL,
  "introduction" TEXT NOT NULL,
  "marketTitle" TEXT NOT NULL,
  "marketCopy" TEXT NOT NULL,
  "localDetails" JSONB NOT NULL,
  "serviceArea" TEXT NOT NULL,
  "published" BOOLEAN NOT NULL DEFAULT false,
  "displayOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "LocationPage_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "LocationPage_slug_key" ON "LocationPage"("slug");
CREATE INDEX "LocationPage_published_displayOrder_idx" ON "LocationPage"("published", "displayOrder");

INSERT INTO "LocationPage" (
  "id", "slug", "city", "county", "seoTitle", "seoDescription",
  "heroLead", "introduction", "marketTitle", "marketCopy", "localDetails",
  "serviceArea", "published", "displayOrder"
)
VALUES
('location_fort_collins', 'fort-collins', 'Fort Collins', 'Larimer County', 'Fort Collins Real Estate Photography & Video | Helios', 'Premium real estate photography, cinematic video, drone media, vertical reels, and listing content for Fort Collins agents and properties.', 'Intentional real estate photography and cinematic media for listings across Fort Collins.', 'Fort Collins listings compete on more than square footage. Buyers are responding to lifestyle, setting, and the feeling of a home—from historic character near Old Town to modern design along the city’s growing edges. Helios builds each visual story to make that distinction clear.', 'Fort Collins deserves more than a standard photo set.', 'A craftsman near City Park, a foothills-view acreage, and a contemporary southeast Fort Collins home should never be marketed the same way. We shape the photography, motion, aerial perspective, and social assets around what makes each property matter—then deliver a polished collection agents can use everywhere.', '["Old Town and central Fort Collins character homes","Southeast Fort Collins and Harmony corridor listings","Foothills, reservoir, and acreage properties","Agent branding and community-focused content"]'::jsonb, 'Serving Fort Collins, Laporte, Bellvue, and nearby Northern Colorado communities.', true, 0),
('location_loveland', 'loveland', 'Loveland', 'Larimer County', 'Loveland Real Estate Photography & Video | Helios', 'Luxury real estate photography, cinematic films, drone coverage, and social media content for Loveland, Colorado listings and agents.', 'Elevated listing media for Loveland homes, communities, and the agents who represent them.', 'Loveland brings together established neighborhoods, fast-moving new construction, lake communities, acreage, and unmistakable foothills access. Our job is to translate those advantages into a visual experience that buyers understand immediately.', 'Show the property—and the Loveland lifestyle around it.', 'The strongest Loveland marketing reveals more than rooms. It can establish proximity to the foothills, capture water and open-space relationships, communicate a thoughtful remodel, or give a new-build listing the warmth it needs to stand apart. Helios plans each shoot around that larger story.', '["Downtown Loveland and established central neighborhoods","West Loveland foothills and acreage properties","Centerra, Lakes at Centerra, and new construction","Lake, golf, and lifestyle-driven community media"]'::jsonb, 'Serving Loveland, Berthoud, Campion, Masonville, and surrounding communities.', true, 1),
('location_windsor', 'windsor', 'Windsor', 'Weld and Larimer Counties', 'Windsor Real Estate Photography & Video | Helios', 'Professional property photography, cinematic video, drone media, and vertical reels for real estate listings throughout Windsor, Colorado.', 'Refined real estate media for Windsor’s homes, neighborhoods, and destination communities.', 'Windsor buyers are often choosing between a home, a neighborhood, and an entire way of living. Strong listing media must communicate all three. Helios combines architectural precision with cinematic storytelling so the property feels connected to the community around it.', 'Turn Windsor’s community value into a visual advantage.', 'From Water Valley and RainDance to custom homes, golf communities, and growing east-side neighborhoods, Windsor listings benefit from context. We use photography, aerial media, film, and social-first content to show scale, amenities, setting, and the details buyers remember.', '["Water Valley, RainDance, and golf-community listings","New construction and builder inventory","Custom homes and luxury properties","Community amenities, trails, and aerial context"]'::jsonb, 'Serving Windsor, Severance, Timnath, and nearby Northern Colorado communities.', true, 2),
('location_greeley', 'greeley', 'Greeley', 'Weld County', 'Greeley Real Estate Photography & Video | Helios', 'Professional real estate photography, aerial media, cinematic video, and listing marketing for agents and properties in Greeley, Colorado.', 'Clear, polished property storytelling for Greeley listings at every scale.', 'Greeley’s market spans first-time-buyer homes, established neighborhoods, new construction, investment properties, luxury residences, and nearby acreage. Helios gives each listing the level of intention it needs to compete—without forcing every property into the same visual formula.', 'Every Greeley listing should feel deliberately presented.', 'Professional media builds confidence before a showing ever begins. We photograph spaces honestly and beautifully, use aerial coverage when location or land matters, and create film and social assets that help agents carry the listing story beyond the MLS.', '["Established central and west Greeley neighborhoods","New construction and growing residential communities","Acreage, equestrian, and rural-edge properties","Investor, rental, and commercial media needs"]'::jsonb, 'Serving Greeley, Evans, Garden City, Eaton, and surrounding Weld County communities.', true, 3),
('location_timnath', 'timnath', 'Timnath', 'Larimer County', 'Timnath Real Estate Photography & Video | Helios', 'Premium real estate photography, cinematic films, drone media, and social content for Timnath, Colorado homes, agents, and builders.', 'Modern listing media designed for Timnath’s homes, builders, and fast-growing communities.', 'Timnath is defined by new communities, thoughtful amenities, open views, and a growing collection of highly designed homes. The visual presentation should feel as current and considered as the property itself.', 'Modern homes need modern storytelling.', 'Helios creates crisp architectural photography, cinematic movement, aerial context, and vertical content that helps Timnath listings stand apart from similar inventory. For builders and agents, that same system creates a consistent visual standard across multiple homes and campaigns.', '["Timnath Ranch and amenity-rich communities","Luxury and custom residential properties","Builder inventory and model-home content","Reservoir, open-space, and Front Range perspectives"]'::jsonb, 'Serving Timnath, Fort Collins, Windsor, and nearby Larimer County communities.', true, 4),
('location_severance', 'severance', 'Severance', 'Weld County', 'Severance Real Estate Photography & Video | Helios', 'Real estate photography, drone media, cinematic video, and social content for Severance, Colorado listings and real estate professionals.', 'Property media that gives Severance listings space, context, and a stronger sense of place.', 'Severance continues to attract buyers looking for newer homes, more room, community amenities, and access to the wider Northern Colorado region. Great media should make those advantages visible before buyers ever arrive.', 'Give buyers the full picture of life in Severance.', 'We combine clean interior and exterior photography with aerial views, cinematic film, and short-form content to show how the home, lot, neighborhood, and surrounding landscape work together. The result is a listing presentation that feels complete—not generic.', '["Newer residential communities and builder listings","Large-lot and semi-rural properties","Mountain-view and open-space positioning","Agent-led neighborhood and community content"]'::jsonb, 'Serving Severance, Windsor, Eaton, Greeley, and surrounding Weld County communities.', true, 5);
