import { prisma } from "@/lib/prisma";
import InquiryManager, { type AdminInquiry, type AdminUserOption } from "./InquiryManager";

export const dynamic = "force-dynamic";
export default async function InquiriesPage() {
  const [inquiries, users] = await Promise.all([prisma.inquiry.findMany({ orderBy: [{ status: "asc" }, { createdAt: "desc" }], include: { requestedServices: { include: { service: { select: { id: true, name: true } } } }, assignedTo: { select: { id: true, displayName: true } }, notes: { orderBy: { createdAt: "desc" }, include: { author: { select: { displayName: true } } }, take: 25 }, activities: { orderBy: { createdAt: "desc" }, include: { actor: { select: { displayName: true } } }, take: 25 } } }), prisma.adminUser.findMany({ where: { active: true }, orderBy: { displayName: "asc" }, select: { id: true, displayName: true, role: true } })]);
  const serialized: AdminInquiry[] = inquiries.map((item) => ({ ...item, desiredDate: item.desiredDate?.toISOString() ?? null, followUpAt: item.followUpAt?.toISOString() ?? null, createdAt: item.createdAt.toISOString(), updatedAt: item.updatedAt.toISOString(), lastActivityAt: item.lastActivityAt.toISOString(), notes: item.notes.map((note) => ({ ...note, createdAt: note.createdAt.toISOString() })), activities: item.activities.map((activity) => ({ ...activity, metadata: activity.metadata as Record<string, unknown> | null, createdAt: activity.createdAt.toISOString() })) }));
  return <div className="space-y-7"><section className="flex flex-col gap-5 border-b border-white/[0.08] pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-[var(--helios-orange)]">Sales pipeline</p><h1 className="mt-3 text-3xl font-light tracking-[-0.03em] text-white sm:text-4xl">Inquiries</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/40">Qualify incoming projects, assign ownership, schedule follow-up, and understand which campaigns generate business.</p></div><a href="/api/admin/inquiries/export" className="admin-btn-secondary">Export CSV</a></section><InquiryManager initialInquiries={serialized} users={users as AdminUserOption[]} /></div>;
}
