"use client";
import { useState } from "react";
export default function BookingRequestForm() {
  const [renderedAt] = useState(() => Date.now()); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage(""); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form));
    try { const response = await fetch("/api/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, renderedAt, consent: data.consent === "on", sourcePage: "/book", ctaName: "Booking Request", message: `Requested services: ${data.services || "Not specified"}\nPreferred date or range: ${data.dateRange || "Not specified"}\n\n${data.notes || ""}` }) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || "Your booking request could not be sent."); form.reset(); setMessage("Your request is in. Helios will contact you directly."); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Your booking request could not be sent."); } finally { setBusy(false); }
  }
  const field = "mt-2 min-h-12 w-full rounded-sm border border-white/15 bg-black/25 px-4 py-3 text-white outline-none focus:border-[#f06b24]";
  return <form onSubmit={submit} className="mt-10 grid gap-5 rounded-sm border border-white/10 bg-white/[0.025] p-6 sm:grid-cols-2 sm:p-8"><input name="website" tabIndex={-1} autoComplete="off" className="hidden" aria-hidden /><label className="text-xs uppercase tracking-[.14em] text-white/40">Name<input required name="name" className={field} /></label><label className="text-xs uppercase tracking-[.14em] text-white/40">Email<input required type="email" name="email" className={field} /></label><label className="text-xs uppercase tracking-[.14em] text-white/40">Phone<input name="phone" className={field} /></label><label className="text-xs uppercase tracking-[.14em] text-white/40">Preferred date or range<input name="dateRange" className={field} placeholder="August 4–7" /></label><label className="text-xs uppercase tracking-[.14em] text-white/40 sm:col-span-2">Property address<input name="propertyAddress" className={field} /></label><label className="text-xs uppercase tracking-[.14em] text-white/40 sm:col-span-2">Requested services<textarea required rows={3} name="services" className={field} /></label><label className="text-xs uppercase tracking-[.14em] text-white/40 sm:col-span-2">Additional notes<textarea rows={4} name="notes" className={field} /></label><label className="flex gap-3 text-sm leading-6 text-white/45 sm:col-span-2"><input required type="checkbox" name="consent" className="mt-1 accent-[#f06b24]" />I agree that Helios may contact me about this booking request.</label><div className="sm:col-span-2"><button disabled={busy} className="min-h-12 bg-[#f06b24] px-7 text-xs font-semibold uppercase tracking-[.17em] text-white disabled:opacity-50">{busy ? "Sending…" : "Request booking"}</button>{message && <p role="status" className="mt-4 text-sm text-white/60">{message}</p>}</div></form>;
}
