"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import type { NewsletterSeries } from "../types";

const initial: NewsletterSeries = { id: "", name: "", description: "", active: true, groupIds: [], individualRecipientIds: [], senderName: "Helios Real Estate Media", replyTo: "", brandInstructions: "Polished, warm, editorial, and grounded in verified Helios content.", goals: "", defaultCta: "", timezone: "America/Denver", generationRule: "FIRST_MONDAY", sendRule: "SECOND_THURSDAY_09:00" };
const input = "mt-2 w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-white outline-none focus:border-[var(--helios-orange)]";
type Group = { id: string; name: string; count: number };

export default function SeriesForm({ seriesId }: { seriesId?: string }) {
  const router = useRouter(); const [draft, setDraft] = useState(initial); const [groups, setGroups] = useState<Group[]>([]);
  const [busy, setBusy] = useState(Boolean(seriesId)); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { void (async () => { try { const response = await fetch(seriesId ? `/api/admin/newsletters/series/${seriesId}` : "/api/admin/newsletters/series/options"); const result = await response.json(); if (result.groups) setGroups(result.groups); if (result.series) setDraft(result.series); } finally { setBusy(false); } })(); }, [seriesId]);
  function patch<K extends keyof NewsletterSeries>(key: K, value: NewsletterSeries[K]) { setDraft(current => ({ ...current, [key]: value })); }
  async function save() { setBusy(true); setMessage("Saving…"); try { const response = await fetch(seriesId ? `/api/admin/newsletters/series/${seriesId}` : "/api/admin/newsletters/series", { method: seriesId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || "Series could not be saved."); setMessage("Series saved."); router.push("/admin/newsletter-studio"); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Series could not be saved."); } finally { setBusy(false); } }
  return <div className="space-y-7">
    <section className="flex flex-col gap-5 border-b border-white/[0.08] pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-[var(--helios-orange)]">Newsletter Studio</p><h1 className="mt-3 text-3xl font-light text-white sm:text-4xl">{seriesId ? "Edit newsletter series" : "Create newsletter series"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/40">Set the recurring editorial brief, audience, generation date, and intended send date.</p></div><button disabled={busy || !draft.name.trim()} onClick={save} className="admin-btn-primary">{busy ? "Working…" : "Save series"}</button></section>
    <nav aria-label="Newsletter series sections" className="sticky top-3 z-20 flex gap-2 overflow-x-auto rounded-xl border border-white/[0.08] bg-[#111]/95 p-2 shadow-xl backdrop-blur">
      {[["01","Series details","series-details"],["02","Audience","default-audience"],["03","Editorial","editorial-direction"],["04","Schedule","recurring-schedule"]].map(([step,label,id]) => <a key={id} href={`#${id}`} className="shrink-0 rounded-lg px-3 py-2 text-xs text-white/50 transition hover:bg-white/[0.05] hover:text-white"><span className="mr-2 text-[var(--helios-orange)]">{step}</span>{label}</a>)}
    </nav>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_20rem]"><main className="space-y-8">
      <Card id="series-details" title="Series details" step="01"><div className="grid gap-5 sm:grid-cols-2"><Field label="Internal series name"><input className={input} value={draft.name} onChange={e => patch("name", e.target.value)} /></Field><Field label="Default sender"><input className={input} value={draft.senderName} onChange={e => patch("senderName", e.target.value)} /></Field></div><Field label="Purpose"><textarea rows={3} className={input} value={draft.description} onChange={e => patch("description", e.target.value)} /></Field><Field label="Reply-to address"><input type="email" className={input} value={draft.replyTo} onChange={e => patch("replyTo", e.target.value)} /></Field></Card>
      <Card id="default-audience" title="Default audience" step="02"><p className="text-sm text-white/35">Newsletter Studio uses Email Studio eligibility and suppression rules again at send time.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{groups.map(group => <label key={group.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-white/[0.08] p-4 text-sm text-white/60"><input type="checkbox" checked={draft.groupIds.includes(group.id)} onChange={() => patch("groupIds", draft.groupIds.includes(group.id) ? draft.groupIds.filter(id => id !== group.id) : [...draft.groupIds, group.id])} /><span className="min-w-0 flex-1 truncate">{group.name}</span><span className="text-xs text-white/25">{group.count}</span></label>)}</div></Card>
      <Card id="editorial-direction" title="Editorial direction" step="03"><Field label="Brand and tone instructions"><textarea rows={4} className={input} value={draft.brandInstructions} onChange={e => patch("brandInstructions", e.target.value)} /></Field><Field label="Newsletter goals"><textarea rows={3} className={input} value={draft.goals} onChange={e => patch("goals", e.target.value)} /></Field><Field label="Default call to action"><input className={input} value={draft.defaultCta} onChange={e => patch("defaultCta", e.target.value)} /></Field></Card>
      <Card id="recurring-schedule" title="Recurring schedule" step="04"><div className="grid gap-5 sm:grid-cols-2"><Field label="Generate draft"><select className={input} value={draft.generationRule} onChange={e => patch("generationRule", e.target.value)}><option value="FIRST_MONDAY">First Monday monthly</option><option value="FIRST_DAY">First day monthly</option><option value="SEVEN_DAYS_BEFORE_SEND">7 days before send</option><option value="MANUAL">Manual only</option></select></Field><Field label="Intended send"><select className={input} value={draft.sendRule} onChange={e => patch("sendRule", e.target.value)}><option value="SECOND_THURSDAY_09:00">Second Thursday · 9:00 AM</option><option value="FIRST_TUESDAY_09:00">First Tuesday · 9:00 AM</option><option value="LAST_THURSDAY_09:00">Last Thursday · 9:00 AM</option></select></Field></div><Field label="Time zone"><select className={input} value={draft.timezone} onChange={e => patch("timezone", e.target.value)}><option value="America/Denver">America/Denver (Mountain Time)</option></select></Field></Card>
    </main><aside><section className="rounded-2xl border border-white/[0.07] bg-white/[0.018] p-5 xl:sticky xl:top-24"><p className="text-[0.58rem] font-semibold uppercase tracking-[.18em] text-white/25">Approval safeguard</p><h2 className="mt-3 text-lg font-light text-white/80">Manual approval is required.</h2><p className="mt-3 text-sm leading-6 text-white/35">AI can prepare each edition, but it cannot approve, schedule, or send it. An edition that misses approval will not be sent late.</p><label className="mt-5 flex items-center gap-3 text-sm text-white/60"><input type="checkbox" checked={draft.active} onChange={e => patch("active", e.target.checked)} />Series active</label></section></aside></div>
    {message && <p role="status" className="text-sm text-white/60">{message}</p>}
  </div>;
}
function Card({ id, title, step, children }: { id: string; title: string; step: string; children: React.ReactNode }) { return <section id={id} tabIndex={-1} className="scroll-mt-24 space-y-6 rounded-2xl border border-white/[0.08] bg-[#111] p-5 outline-none focus-visible:ring-2 focus-visible:ring-[var(--helios-orange)] sm:p-7"><div><p className="text-[0.56rem] font-semibold uppercase tracking-[.16em] text-[var(--helios-orange)]">{step}</p><h2 className="mt-2 text-2xl font-light text-white">{title}</h2></div>{children}</section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs text-white/40">{label}{children}</label>; }
