CREATE TYPE "InquiryStatus" AS ENUM ('NEW', 'CONTACTED', 'QUALIFIED', 'BOOKED', 'CLOSED', 'SPAM');
CREATE TABLE "Inquiry" ("id" TEXT NOT NULL, "status" "InquiryStatus" NOT NULL DEFAULT 'NEW', "name" TEXT NOT NULL, "email" TEXT NOT NULL, "phone" TEXT, "propertyAddress" TEXT, "city" TEXT, "state" TEXT, "postalCode" TEXT, "desiredDate" TIMESTAMP(3), "message" TEXT, "sourcePage" TEXT, "referrer" TEXT, "ctaName" TEXT, "utmSource" TEXT, "utmMedium" TEXT, "utmCampaign" TEXT, "utmContent" TEXT, "utmTerm" TEXT, "ipHash" TEXT, "userAgent" TEXT, "consent" BOOLEAN NOT NULL DEFAULT false, "assignedToId" TEXT, "followUpAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "lastActivityAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Inquiry_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InquiryService" ("inquiryId" TEXT NOT NULL, "serviceId" TEXT NOT NULL, CONSTRAINT "InquiryService_pkey" PRIMARY KEY ("inquiryId","serviceId"));
CREATE TABLE "InquiryNote" ("id" TEXT NOT NULL, "inquiryId" TEXT NOT NULL, "authorId" TEXT NOT NULL, "body" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "InquiryNote_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InquiryActivity" ("id" TEXT NOT NULL, "inquiryId" TEXT NOT NULL, "actorId" TEXT, "action" TEXT NOT NULL, "summary" TEXT NOT NULL, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "InquiryActivity_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Inquiry_status_createdAt_idx" ON "Inquiry"("status", "createdAt");
CREATE INDEX "Inquiry_assignedToId_status_idx" ON "Inquiry"("assignedToId", "status");
CREATE INDEX "Inquiry_followUpAt_idx" ON "Inquiry"("followUpAt");
CREATE INDEX "Inquiry_ipHash_createdAt_idx" ON "Inquiry"("ipHash", "createdAt");
CREATE INDEX "InquiryService_serviceId_idx" ON "InquiryService"("serviceId");
CREATE INDEX "InquiryNote_inquiryId_createdAt_idx" ON "InquiryNote"("inquiryId", "createdAt");
CREATE INDEX "InquiryNote_authorId_idx" ON "InquiryNote"("authorId");
CREATE INDEX "InquiryActivity_inquiryId_createdAt_idx" ON "InquiryActivity"("inquiryId", "createdAt");
CREATE INDEX "InquiryActivity_actorId_idx" ON "InquiryActivity"("actorId");
ALTER TABLE "Inquiry" ADD CONSTRAINT "Inquiry_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "InquiryService" ADD CONSTRAINT "InquiryService_inquiryId_fkey" FOREIGN KEY ("inquiryId") REFERENCES "Inquiry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InquiryService" ADD CONSTRAINT "InquiryService_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InquiryNote" ADD CONSTRAINT "InquiryNote_inquiryId_fkey" FOREIGN KEY ("inquiryId") REFERENCES "Inquiry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InquiryNote" ADD CONSTRAINT "InquiryNote_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "AdminUser"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InquiryActivity" ADD CONSTRAINT "InquiryActivity_inquiryId_fkey" FOREIGN KEY ("inquiryId") REFERENCES "Inquiry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InquiryActivity" ADD CONSTRAINT "InquiryActivity_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
