"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function LoginForm({ next }: { next: string }) {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const response = await fetch("/api/admin/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok || data.success !== true) throw new Error(data.error || "Unable to sign in."); router.replace(next); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to sign in."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-[0.55rem] font-semibold uppercase tracking-[0.16em] text-white/35">Email<input type="email" autoComplete="username" required value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3.5 text-sm normal-case tracking-normal text-white outline-none focus:border-[var(--helios-orange)]" /></label><label className="block text-[0.55rem] font-semibold uppercase tracking-[0.16em] text-white/35">Password<input type="password" autoComplete="current-password" required value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3.5 text-sm normal-case tracking-normal text-white outline-none focus:border-[var(--helios-orange)]" /></label>{error && <p role="alert" className="rounded-xl border border-red-400/20 bg-red-400/[0.06] px-4 py-3 text-sm text-red-200/80">{error}</p>}<button type="submit" disabled={busy} className="admin-btn-primary w-full rounded-xl">{busy ? "Signing in…" : "Enter workspace"}</button></form>;
}
