"use client";
import { useState } from "react";

export type ProjectOption = { id: string; title: string; slug: string };
export type Placement = { id: string; projectId: string; titleOverride: string | null; displayOrder: number; active: boolean; imageUrl: string | null; project: { title: string; slug: string; status: string; locationLabel: string | null; heroMedia: { storageKey: string | null; altText: string | null } | null } };

export default function HomepageProjectManager({ initialPlacements, projects }: { initialPlacements: Placement[]; projects: ProjectOption[] }) {
  const [placements, setPlacements] = useState(initialPlacements); const [selected, setSelected] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const available = projects.filter((project) => !placements.some((item) => item.projectId === project.id));
  async function request(url: string, options: RequestInit) { const response = await fetch(url, { ...options, headers: { "Content-Type": "application/json" } }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || "The change could not be saved."); return data; }
  async function add() { if (!selected) return; setBusy(true); setError(null); try { const data = await request("/api/admin/homepage-projects", { method: "POST", body: JSON.stringify({ projectId: selected }) }); setPlacements((current) => [...current, { ...data.placement, imageUrl: null }]); setSelected(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to add project."); } finally { setBusy(false); } }
  async function update(item: Placement, patch: { active?: boolean; titleOverride?: string }) { setBusy(true); setError(null); try { const data = await request("/api/admin/homepage-projects", { method: "PATCH", body: JSON.stringify({ placementId: item.id, ...patch }) }); setPlacements((current) => current.map((entry) => entry.id === item.id ? { ...entry, ...data.placement } : entry)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update project."); } finally { setBusy(false); } }
  async function remove(item: Placement) { setBusy(true); setError(null); try { await request(`/api/admin/homepage-projects?placementId=${item.id}`, { method: "DELETE" }); setPlacements((current) => current.filter(({ id }) => id !== item.id)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to remove project."); } finally { setBusy(false); } }
  return <><section className="rounded-2xl border border-white/[0.08] bg-white/[0.02] p-5"><div className="flex flex-col gap-3 sm:flex-row"><select value={selected} onChange={(event) => setSelected(event.target.value)} disabled={placements.length >= 1} className="min-h-11 flex-1 rounded-xl border border-white/10 bg-[#111] px-4 text-sm text-white"><option value="">Select a published project</option>{available.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</select><button type="button" onClick={add} disabled={!selected || busy || placements.length >= 1} className="rounded-full bg-[var(--helios-orange)] px-6 py-3 text-[0.54rem] font-semibold uppercase tracking-[0.14em] text-black disabled:opacity-35">Set Featured Project</button></div><p className="mt-3 text-xs text-white/25">{placements.length ? "Featured Project configured" : "No Featured Project selected"}</p></section>{error && <p role="alert" className="rounded-xl border border-red-400/20 bg-red-400/[0.06] p-4 text-sm text-red-200/75">{error}</p>}<section className="space-y-4">{placements.map((item) => <article key={item.id} className={`grid overflow-hidden rounded-2xl border bg-[#111] sm:grid-cols-[13rem_minmax(0,1fr)] ${item.active ? "border-white/[0.09]" : "border-white/[0.05] opacity-65"}`}><div className="relative min-h-44 bg-white/[0.03]">{item.imageUrl ? <>
    {/* eslint-disable-next-line @next/next/no-img-element */}
    <img src={item.imageUrl} alt="" className="absolute inset-0 h-full w-full object-cover" />
  </> : <div className="flex h-full items-center justify-center text-xs text-white/20">Hero image required</div>}<span className="absolute left-3 top-3 rounded-full bg-black/70 px-3 py-1 text-[0.5rem] uppercase tracking-[0.13em] text-white/60">Featured Project</span></div><div className="p-5"><h2 className="text-lg text-white/80">{item.project.title}</h2><p className="mt-1 text-xs text-white/25">/{item.project.slug}</p><label className="mt-5 block text-[0.52rem] uppercase tracking-[0.14em] text-white/30">Homepage title<input defaultValue={item.titleOverride ?? ""} placeholder={item.project.title} onBlur={(event) => void update(item, { titleOverride: event.target.value })} className="mt-2 w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-sm normal-case tracking-normal text-white" /></label><div className="mt-5 flex flex-wrap items-center gap-2 border-t border-white/[0.06] pt-4"><button disabled={busy} onClick={() => update(item, { active: !item.active })} className="ml-auto text-[0.52rem] uppercase tracking-[0.13em] text-white/35">{item.active ? "Hide" : "Show"}</button><button disabled={busy} onClick={() => remove(item)} className="text-[0.52rem] uppercase tracking-[0.13em] text-red-200/40">Remove</button></div></div></article>)}{placements.length === 0 && <div className="rounded-2xl border border-dashed border-white/10 py-16 text-center"><p className="font-display text-4xl font-light text-white/30">No Featured Project selected.</p><p className="mt-3 text-sm text-white/20">The five service cards will lead the section.</p></div>}</section></>;
}
