"use client";

import { useState } from "react";
import type { PublicContentCard, PublicNavigationItem, PublicSiteSettings } from "@/lib/site-settings";

type ListKey = "standardPrinciples" | "approachCards";
type NavKey = "headerNavigation" | "footerNavigation";

export default function HomepageStructureManager({ initialSettings }: { initialSettings: PublicSiteSettings }) {
  const [settings, setSettings] = useState(initialSettings);
  const [message, setMessage] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const updateCard = (key: ListKey, index: number, patch: Partial<PublicContentCard>) => setSettings((current) => ({ ...current, [key]: current[key].map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) }));
  const updateNav = (key: NavKey, index: number, patch: Partial<PublicNavigationItem>) => setSettings((current) => ({ ...current, [key]: current[key].map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) }));
  const addNav = (key: NavKey) => setSettings((current) => ({ ...current, [key]: [...current[key], { label: "New link", href: "/", published: true }] }));
  const removeNav = (key: NavKey, index: number) => setSettings((current) => ({ ...current, [key]: current[key].filter((_, itemIndex) => itemIndex !== index) }));
  const move = (key: ListKey | NavKey, index: number, direction: -1 | 1) => setSettings((current) => { const list = [...current[key]]; const target = index + direction; if (target < 0 || target >= list.length) return current; [list[index], list[target]] = [list[target], list[index]]; return { ...current, [key]: list } as PublicSiteSettings; });
  async function save() { setSaving(true); setMessage(null); try { const response = await fetch("/api/admin/site-settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setSettings(result.settings); setMessage("Homepage structure and navigation saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save."); } finally { setSaving(false); } }

  return <section className="mt-7 rounded-2xl border border-white/[0.08] bg-[#111] p-6 lg:p-8"><p className="eyebrow text-[var(--helios-orange)]">Reusable structure</p><h2 className="mt-3 text-2xl font-light text-white">Principles, approach, and navigation</h2><div className="mt-7 grid gap-7 xl:grid-cols-2">
    {(["standardPrinciples", "approachCards"] as ListKey[]).map((key) => <div key={key}><h3 className="text-lg text-white">{key === "standardPrinciples" ? "Our Standard cards" : "Our Approach cards"}</h3><div className="mt-4 space-y-3">{settings[key].map((item, index) => <div key={`${key}-${index}`} className="rounded-xl border border-white/10 bg-black/25 p-4"><div className="grid gap-3 sm:grid-cols-[5rem_1fr]"><input aria-label="Card number" value={item.number} onChange={(event) => updateCard(key, index, { number: event.target.value })} className="input"/><input aria-label="Card title" value={item.title} onChange={(event) => updateCard(key, index, { title: event.target.value })} className="input"/></div><textarea aria-label="Card description" rows={3} value={item.description} onChange={(event) => updateCard(key, index, { description: event.target.value })} className="input resize-y"/><div className="mt-3 flex items-center justify-between"><label className="text-xs text-white/50"><input type="checkbox" checked={item.published !== false} onChange={(event) => updateCard(key, index, { published: event.target.checked })}/> Published</label><div><button type="button" onClick={() => move(key, index, -1)} className="admin-btn-link">Up</button><button type="button" onClick={() => move(key, index, 1)} className="admin-btn-link">Down</button></div></div></div>)}</div></div>)}
    {(["headerNavigation", "footerNavigation"] as NavKey[]).map((key) => <div key={key}><div className="flex items-center justify-between gap-3"><h3 className="text-lg text-white">{key === "headerNavigation" ? "Header navigation" : "Footer navigation"}</h3><button type="button" onClick={() => addNav(key)} className="admin-btn-secondary">Add link</button></div><div className="mt-4 space-y-3">{settings[key].map((item, index) => <div key={`${key}-${index}`} className="rounded-xl border border-white/10 bg-black/25 p-4"><div className="grid gap-3 sm:grid-cols-2"><input aria-label="Navigation label" value={item.label} onChange={(event) => updateNav(key, index, { label: event.target.value })} className="input"/><input aria-label="Navigation destination" list="site-destinations" value={item.href} onChange={(event) => updateNav(key, index, { href: event.target.value })} className="input"/></div><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-4 text-xs text-white/50"><label><input type="checkbox" checked={item.published !== false} onChange={(event) => updateNav(key, index, { published: event.target.checked })}/> Published</label><label><input type="checkbox" checked={Boolean(item.newTab)} onChange={(event) => updateNav(key, index, { newTab: event.target.checked })}/> New tab</label></div><div><button type="button" onClick={() => move(key, index, -1)} className="admin-btn-link">Up</button><button type="button" onClick={() => move(key, index, 1)} className="admin-btn-link">Down</button><button type="button" onClick={() => removeNav(key, index)} className="admin-btn-link-destructive">Remove</button></div></div></div>)}</div></div>)}
  </div><datalist id="site-destinations"><option value="/"/><option value="/portfolio"/><option value="/services"/><option value="/about"/><option value="/faq"/><option value="/client-portal"/><option value="/#testimonials"/></datalist><div className="mt-7 flex items-center justify-between gap-4 border-t border-white/10 pt-5"><p role="status" className="text-sm text-white/40">{message}</p><button type="button" onClick={() => void save()} disabled={saving} className="admin-btn-primary">{saving ? "Saving…" : "Save structure"}</button></div></section>;
}
