"use client";
import { useEffect,useMemo,useRef } from "react";

export default function ViewportVideoFrame({src,title,className,autoplay,projectId,mediaId}:{src:string;title:string;className:string;autoplay:boolean;projectId?:string;mediaId?:string}){
 const ref=useRef<HTMLIFrameElement>(null);
 const source=useMemo(()=>{if(!/(youtube\.com|youtu\.be)/i.test(src))return src;const url=new URL(src);url.searchParams.set("enablejsapi","1");url.searchParams.set("playsinline","1");if(autoplay)url.searchParams.set("mute","1");return url.toString();},[autoplay,src]);
 useEffect(()=>{const frame=ref.current;if(!frame||!/(youtube\.com|youtu\.be)/i.test(src))return;const emit=(eventName:string,milestone?:number)=>window.dispatchEvent(new CustomEvent("helios:portfolio-analytics",{detail:{eventName,projectId,channel:"video",target:`#media-${mediaId||"embed"}`,metadata:milestone?{milestone}:undefined,onceKey:`${eventName}:${projectId}:${mediaId||title}`}}));const message=(event:MessageEvent)=>{if(event.source!==frame.contentWindow)return;try{const data=typeof event.data==="string"?JSON.parse(event.data):event.data;if(data?.event==="onStateChange"&&data.info===1)emit("VIDEO_START");if(data?.event==="onStateChange"&&data.info===0)emit("VIDEO_COMPLETE",100);if(data?.event==="infoDelivery"&&data.info?.duration&&data.info?.currentTime){const ratio=data.info.currentTime/data.info.duration;if(ratio>=.75)emit("VIDEO_PROGRESS_75",75);else if(ratio>=.5)emit("VIDEO_PROGRESS_50",50);else if(ratio>=.25)emit("VIDEO_PROGRESS_25",25);}}catch{}};window.addEventListener("message",message);if(!autoplay)return()=>window.removeEventListener("message",message);const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;const connection=(navigator as Navigator&{connection?:{saveData?:boolean}}).connection;if(reduced||connection?.saveData)return()=>window.removeEventListener("message",message);const command=(func:string)=>frame.contentWindow?.postMessage(JSON.stringify({event:"command",func,args:[]}),"*");const stopOthers=(event:Event)=>{if((event as CustomEvent).detail!==frame)command("pauseVideo");};window.addEventListener("helios:video-active",stopOthers);const observer=new IntersectionObserver(entries=>{const visible=(entries[0]?.intersectionRatio||0)>=.65;if(visible){window.dispatchEvent(new CustomEvent("helios:video-active",{detail:frame}));command("mute");command("playVideo");window.dispatchEvent(new CustomEvent("helios:video-engagement",{detail:{action:"viewport-play",title}}));}else command("pauseVideo");},{threshold:[0,.65,.8]});observer.observe(frame);return()=>{observer.disconnect();window.removeEventListener("message",message);window.removeEventListener("helios:video-active",stopOthers);command("pauseVideo");};},[autoplay,mediaId,projectId,src,title]);
 return <iframe ref={ref} src={source} title={title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" className={className}/>;
}
