import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { visibleSocialConnections } from "./visible-connections.ts";

const read=(path:string)=>readFileSync(new URL(`../../${path}`,import.meta.url),"utf8");
test("Meta OAuth discovers real Pages and linked Instagram destinations without retired Page fields",()=>{const source=read("lib/social/meta.ts");assert.match(source,/me\/accounts\?fields=id,name,access_token,instagram_business_account/);assert.doesNotMatch(source,/\btasks\b/);assert.doesNotMatch(source,/pending-\$\{/);assert.match(source,/FACEBOOK:/);assert.match(source,/INSTAGRAM:/);});
test("Meta OAuth uses and requires the Facebook Login for Business configuration",()=>{const connect=read("app/api/admin/social/oauth/[provider]/connect/route.ts");const oauth=read("lib/social/oauth.ts");const meta=read("lib/social/meta.ts");const providers=read("lib/social/providers.ts");const env=read(".env.example");assert.match(connect,/config_id/);assert.match(connect,/provider==="meta" && !config\.configurationId/);assert.match(oauth,/META_LOGIN_CONFIG_ID/);assert.match(meta,/business_management/);assert.match(providers,/META_LOGIN_CONFIG_ID/);assert.match(env,/META_LOGIN_CONFIG_ID/);});
test("OAuth state is expiring, single-use, workspace and administrator scoped",()=>{const connect=read("app/api/admin/social/oauth/[provider]/connect/route.ts");const callback=read("app/api/admin/social/oauth/[provider]/callback/route.ts");assert.match(connect,/stateHash:hashOAuthState/);assert.match(connect,/10\*60_000/);assert.match(callback,/oauthSession\.consumedAt/);assert.match(callback,/oauthSession\.userId!==session\.userId/);assert.match(callback,/oauthSession\.workspaceId!==actualWorkspaceId/);});
test("destination selection never returns Page tokens to the browser",()=>{const source=read("lib/social/meta.ts");assert.match(source,/publicDestination/);assert.doesNotMatch(source.match(/publicDestination[\s\S]+$/)?.[0]||"",/encryptedPageToken:destination/);});
test("publishing remains behind independent rollout flags",()=>{const env=read(".env.example");const publishing=read("lib/social/publishing.ts");for(const flag of ["SOCIAL_META_CONNECTIONS_ENABLED","SOCIAL_FACEBOOK_PUBLISHING_ENABLED","SOCIAL_INSTAGRAM_PUBLISHING_ENABLED"])assert.match(env,new RegExp(flag));assert.match(publishing,/SOCIAL_FACEBOOK_PUBLISHING_ENABLED/);assert.match(publishing,/SOCIAL_INSTAGRAM_PUBLISHING_ENABLED/);});
test("placeholder migration preserves records and requires reconnection",()=>{const migration=read("prisma/migrations/20260823170000_social_studio_meta_destinations/migration.sql");assert.match(migration,/providerAccountId.*LIKE 'pending-%'/s);assert.match(migration,/REAUTHORIZATION_REQUIRED/);assert.doesNotMatch(migration,/DELETE FROM "SocialConnection"/);});
test("legacy platform-only uniqueness is removed without deleting connections",()=>{const migration=read("prisma/migrations/20260823213000_remove_legacy_social_platform_unique/migration.sql");assert.match(migration,/DROP INDEX IF EXISTS "SocialConnection_platform_key"/);assert.doesNotMatch(migration,/DELETE FROM "SocialConnection"/);});
test("real Meta destinations supersede preserved placeholder cards",()=>{const connections=[{id:"legacy-instagram",platform:"INSTAGRAM",providerAccountId:"pending-instagram"},{id:"real-instagram",platform:"INSTAGRAM",providerAccountId:"17841472000193166"},{id:"legacy-facebook",platform:"FACEBOOK",providerAccountId:null},{id:"real-facebook",platform:"FACEBOOK",providerAccountId:"501265666410206"},{id:"linkedin-placeholder",platform:"LINKEDIN",providerAccountId:"pending-linkedin"}];assert.deepEqual(visibleSocialConnections(connections).map(({id})=>id),["real-instagram","real-facebook","linkedin-placeholder"]);});
test("connection testing is read-only and scheduled health checks are present",()=>{const testRoute=read("app/api/admin/social/connections/test/route.ts");const health=read("lib/social/meta-health.ts");assert.match(testRoute,/testMetaConnection/);assert.doesNotMatch(testRoute,/publish\(/);assert.match(health,/tokenExpiresAt/);assert.match(health,/REAUTHORIZATION_REQUIRED/);});
test("send now uses the same protected queue and requires confirmation",()=>{const route=read("app/api/admin/social/campaigns/[campaignId]/route.ts");const editor=read("app/admin/social-studio/campaigns/[campaignId]/SocialCampaignEditor.tsx");assert.match(route,/action === "send-now"/);assert.match(route,/createPublishingJob/);assert.match(editor,/window\.confirm\("Publish this approved revision now/);});
