import { revalidatePath } from "next/cache";
import { NextResponse } from "next/server";
import { recordAuditEvent } from "@/lib/audit";
import { getAdminSession } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { createPreviewToken, hashPreviewToken } from "@/lib/project-preview";
import { getAbsoluteUrl } from "@/lib/site";

type Context = { params: Promise<{ projectId: string }> };
export async function POST(request: Request, { params }: Context) {
  try { const session = await getAdminSession(); if (!session) return NextResponse.json({ success: false, error: "Authentication required." }, { status: 401 }); const { projectId } = await params; const body = await request.json() as Record<string,unknown>; const days = typeof body.days === "number" ? Math.round(body.days) : 7; if (![1,3,7,14,30].includes(days)) return NextResponse.json({ success:false,error:"Choose a valid expiration period."},{status:400}); const label = typeof body.label === "string" ? body.label.trim().slice(0,120) || null : null; const project = await prisma.project.findUnique({where:{id:projectId},select:{slug:true,title:true}}); if(!project)return NextResponse.json({success:false,error:"Project not found."},{status:404}); const token=createPreviewToken(); const preview=await prisma.projectPreviewLink.create({data:{projectId,tokenHash:hashPreviewToken(token),label,createdById:session.userId,expiresAt:new Date(Date.now()+days*86400000)},select:{id:true,label:true,expiresAt:true,createdAt:true,lastUsedAt:true,revokedAt:true}}); const url=getAbsoluteUrl(`/portfolio/${project.slug}?preview=${encodeURIComponent(token)}`); await recordAuditEvent({actorId:session.userId,actorEmail:session.email,action:"PROJECT_PREVIEW_CREATED",entityType:"Project",entityId:projectId,summary:`Preview link created for ${project.title}.`}); revalidatePath(`/admin/projects/${projectId}`); return NextResponse.json({success:true,preview:{...preview,url}},{status:201}); } catch(error){console.error("Unable to create preview:",error);return NextResponse.json({success:false,error:"The preview link could not be created."},{status:500});}
}
export async function DELETE(request: Request,{params}:Context){try{const session=await getAdminSession();if(!session)return NextResponse.json({success:false,error:"Authentication required."},{status:401});const {projectId}=await params;const previewId=new URL(request.url).searchParams.get("previewId");if(!previewId)return NextResponse.json({success:false,error:"Preview ID required."},{status:400});const result=await prisma.projectPreviewLink.updateMany({where:{id:previewId,projectId,revokedAt:null},data:{revokedAt:new Date()}});if(!result.count)return NextResponse.json({success:false,error:"Active preview not found."},{status:404});await recordAuditEvent({actorId:session.userId,actorEmail:session.email,action:"PROJECT_PREVIEW_REVOKED",entityType:"Project",entityId:projectId,summary:"Project preview link revoked."});revalidatePath(`/admin/projects/${projectId}`);return NextResponse.json({success:true});}catch(error){console.error("Unable to revoke preview:",error);return NextResponse.json({success:false,error:"The preview link could not be revoked."},{status:500});}}
