"use client";

import { useState } from "react";
import type { CtaActionType, CtaPlacementSlot } from "@/app/generated/prisma/client";

export type AdminCta = { id: string; internalName: string; eyebrow: string | null; headline: string; body: string | null; primaryLabel: string; primaryActionType: CtaActionType; primaryValue: string | null; secondaryLabel: string | null; secondaryActionType: CtaActionType | null; secondaryValue: string | null; published: boolean; slots: CtaPlacementSlot[]; createdAt: string; updatedAt: string };
type Draft = Omit<AdminCta, "id" | "createdAt" | "updatedAt"> & { id: string | null };
const actionOptions: { value: CtaActionType; label: string }[] = [{ value: "BOOKING", label: "Global booking URL" }, { value: "PHONE", label: "Global phone" }, { value: "EMAIL", label: "Global email" }, { value: "INTERNAL", label: "Internal page" }, { value: "EXTERNAL", label: "External URL" }];
const slotOptions: { value: CtaPlacementSlot; label: string }[] = [{ value: "HOME_PRIMARY", label: "Homepage primary" }, { value: "ABOUT_FOOTER", label: "About footer" }, { value: "SERVICES_FOOTER", label: "Services footer" }, { value: "FAQ_FOOTER", label: "FAQ footer" }, { value: "PORTFOLIO_FOOTER", label: "Portfolio footer" }];
const empty: Draft = { id: null, internalName: "", eyebrow: "", headline: "", body: "", primaryLabel: "Book Your Shoot", primaryActionType: "BOOKING", primaryValue: "", secondaryLabel: "", secondaryActionType: null, secondaryValue: "", published: false, slots: [] };

export default function CtaManager({ initialCtas }: { initialCtas: AdminCta[] }) {
  const [ctas, setCtas] = useState(initialCtas); const [draft, setDraft] = useState<Draft | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  function edit(cta: AdminCta) { setDraft({ id: cta.id, internalName: cta.internalName, eyebrow: cta.eyebrow ?? "", headline: cta.headline, body: cta.body ?? "", primaryLabel: cta.primaryLabel, primaryActionType: cta.primaryActionType, primaryValue: cta.primaryValue ?? "", secondaryLabel: cta.secondaryLabel ?? "", secondaryActionType: cta.secondaryActionType, secondaryValue: cta.secondaryValue ?? "", published: cta.published, slots: cta.slots }); setError(null); }
  async function request(url: string, options: RequestInit) { const response = await fetch(url, { ...options, headers: { "Content-Type": "application/json" } }); const data = await response.json(); if (!response.ok || data.success !== true) throw new Error(data.error || "The change could not be saved."); return data; }
  async function save() { if (!draft) return; setBusy(true); setError(null); try { const data = await request("/api/admin/ctas", { method: draft.id ? "PATCH" : "POST", body: JSON.stringify({ ...draft, ...(draft.id ? { ctaId: draft.id } : {}) }) }); const saved = { ...data.cta, slots: data.cta.placements.map((item: { slot: CtaPlacementSlot }) => item.slot) } as AdminCta; setCtas((current) => current.some(({ id }) => id === saved.id) ? current.map((item) => item.id === saved.id ? saved : item) : [...current, saved]); setDraft(null); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save CTA."); } finally { setBusy(false); } }
  async function remove(cta: AdminCta) { if (!confirm(`Permanently delete “${cta.internalName}”?`)) return; setBusy(true); try { await request(`/api/admin/ctas?ctaId=${encodeURIComponent(cta.id)}`, { method: "DELETE" }); setCtas((current) => current.filter(({ id }) => id !== cta.id)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to delete CTA."); } finally { setBusy(false); } }
  return <>
    {error && <div role="alert" className="rounded-xl border border-red-400/20 bg-red-400/[0.06] px-5 py-4 text-sm text-red-200/80">{error}</div>}
    <section className="rounded-2xl border border-white/[0.08] bg-[#111] p-5 sm:p-7"><div className="flex items-end justify-between gap-5 border-b border-white/[0.08] pb-6"><div><p className="eyebrow text-[var(--helios-orange)]">Reusable library</p><h2 className="mt-2 text-2xl font-light text-white">Conversion messages</h2></div><button type="button" onClick={() => setDraft({ ...empty, slots: [] })} className="admin-btn-primary">Add CTA</button></div>
      <div className="mt-6 grid gap-4 xl:grid-cols-2">{ctas.map((cta) => <article key={cta.id} className="rounded-2xl border border-white/[0.08] bg-black/20 p-6"><div className="flex justify-between gap-4"><div><p className="text-[0.52rem] uppercase tracking-[0.16em] text-[var(--helios-orange)]">{cta.internalName}</p><h3 className="mt-3 font-display text-2xl leading-tight text-white/80">{cta.headline}</h3></div><span className={`h-fit rounded-full border px-2 py-1 text-[0.47rem] uppercase tracking-[0.12em] ${cta.published ? "border-emerald-300/15 text-emerald-200/55" : "border-white/10 text-white/25"}`}>{cta.published ? "Published" : "Draft"}</span></div><p className="mt-4 line-clamp-2 text-sm leading-6 text-white/35">{cta.body || "No supporting copy"}</p><div className="mt-5 flex flex-wrap gap-2">{cta.slots.map((slot) => <span key={slot} className="rounded-full border border-white/10 px-3 py-1 text-[0.48rem] uppercase tracking-[0.11em] text-white/30">{slotOptions.find((item) => item.value === slot)?.label}</span>)}</div><div className="mt-6 flex justify-end gap-2 border-t border-white/[0.06] pt-4"><button onClick={() => edit(cta)} className="admin-btn-link">Edit</button><button disabled={busy} onClick={() => remove(cta)} className="admin-btn-link-destructive">Delete</button></div></article>)}{ctas.length === 0 && <p className="col-span-full py-20 text-center font-display text-3xl text-white/25">No calls to action yet.</p>}</div>
    </section>
    {draft && <div className="fixed inset-0 z-[80] overflow-y-auto bg-black/85 p-5 backdrop-blur-md" role="dialog" aria-modal="true"><div className="mx-auto my-5 max-w-4xl rounded-2xl border border-white/10 bg-[#151515] p-7"><div className="flex justify-between"><div><p className="eyebrow text-[var(--helios-orange)]">Conversion message</p><h2 className="mt-2 text-2xl text-white">{draft.id ? "Edit CTA" : "New CTA"}</h2></div><button onClick={() => setDraft(null)} className="admin-btn-icon-sm">×</button></div><div className="mt-7 grid gap-5 sm:grid-cols-2">
      <Field label="Internal name"><input value={draft.internalName} onChange={(e) => setDraft({ ...draft, internalName: e.target.value })} className="input" /></Field><Field label="Eyebrow"><input value={draft.eyebrow ?? ""} onChange={(e) => setDraft({ ...draft, eyebrow: e.target.value })} className="input" /></Field><div className="sm:col-span-2"><Field label="Headline"><input value={draft.headline} onChange={(e) => setDraft({ ...draft, headline: e.target.value })} className="input" /></Field></div><div className="sm:col-span-2"><Field label="Supporting copy"><textarea rows={4} value={draft.body ?? ""} onChange={(e) => setDraft({ ...draft, body: e.target.value })} className="input resize-y" /></Field></div>
      <ActionFields title="Primary button" label={draft.primaryLabel} type={draft.primaryActionType} value={draft.primaryValue ?? ""} onLabel={(value) => setDraft({ ...draft, primaryLabel: value })} onType={(value) => setDraft({ ...draft, primaryActionType: value })} onValue={(value) => setDraft({ ...draft, primaryValue: value })} />
      <ActionFields title="Secondary button (optional)" label={draft.secondaryLabel ?? ""} type={draft.secondaryActionType ?? "INTERNAL"} value={draft.secondaryValue ?? ""} onLabel={(value) => setDraft({ ...draft, secondaryLabel: value, secondaryActionType: value ? draft.secondaryActionType ?? "INTERNAL" : null })} onType={(value) => setDraft({ ...draft, secondaryActionType: value })} onValue={(value) => setDraft({ ...draft, secondaryValue: value })} />
      <div className="sm:col-span-2"><p className="text-[0.55rem] font-semibold uppercase tracking-[0.16em] text-white/35">Site placements</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{slotOptions.map((slot) => <label key={slot.value} className="flex items-center gap-3 rounded-xl border border-white/10 p-4 text-sm text-white/50"><input type="checkbox" checked={draft.slots.includes(slot.value)} onChange={(e) => setDraft({ ...draft, slots: e.target.checked ? [...draft.slots, slot.value] : draft.slots.filter((item) => item !== slot.value) })} className="accent-[var(--helios-orange)]" />{slot.label}</label>)}</div></div><label className="flex items-center gap-3 text-sm text-white/50"><input type="checkbox" checked={draft.published} onChange={(e) => setDraft({ ...draft, published: e.target.checked })} className="accent-[var(--helios-orange)]" />Published</label>
    </div><div className="mt-7 flex justify-end gap-3 border-t border-white/[0.08] pt-6"><button onClick={() => setDraft(null)} className="admin-btn-secondary">Cancel</button><button disabled={busy || !draft.internalName.trim() || !draft.headline.trim() || !draft.primaryLabel.trim()} onClick={save} className="admin-btn-primary">{busy ? "Saving…" : "Save CTA"}</button></div></div></div>}
  </>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-[0.55rem] font-semibold uppercase tracking-[0.16em] text-white/35">{label}{children}</label>; }
function ActionFields({ title, label, type, value, onLabel, onType, onValue }: { title: string; label: string; type: CtaActionType; value: string; onLabel: (v:string)=>void; onType:(v:CtaActionType)=>void; onValue:(v:string)=>void }) { const needsValue = type === "INTERNAL" || type === "EXTERNAL"; return <fieldset className="rounded-xl border border-white/[0.08] p-4"><legend className="px-2 text-[0.55rem] uppercase tracking-[0.14em] text-white/35">{title}</legend><Field label="Label"><input value={label} onChange={(e)=>onLabel(e.target.value)} className="input" /></Field><Field label="Action"><select value={type} onChange={(e)=>onType(e.target.value as CtaActionType)} className="input bg-[#111]">{actionOptions.map((option)=><option key={option.value} value={option.value}>{option.label}</option>)}</select></Field>{needsValue && <Field label={type === "INTERNAL" ? "Page path" : "Destination URL"}><input value={value} placeholder={type === "INTERNAL" ? "/services" : "https://…"} onChange={(e)=>onValue(e.target.value)} className="input" /></Field>}<p className="mt-3 text-[0.68rem] leading-5 text-white/25">Booking, phone, and email actions inherit their destination from Site Settings.</p></fieldset>; }
