import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import BlogArticleBody from "@/app/components/BlogArticleBody";
import ArticleShareLinks from "@/app/components/ArticleShareLinks";
import Footer from "@/app/components/Footer";
import Navbar from "@/app/components/Navbar";
import { blogImageUrl, readingMinutes } from "@/lib/blog";
import { getAdminSession } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { getSiteSettings } from "@/lib/site-settings";

type Props={params:Promise<{slug:string}>};
async function getPost(slug:string){try{const session=await getAdminSession();return prisma.blogPost.findUnique({where:{slug},include:{featuredMedia:{select:{storageKey:true}},},}).then(post=>{if(!post)return null;if(session)return post;const live=(post.status==="PUBLISHED"&&!!post.publishedAt&&post.publishedAt<=new Date())||(post.status==="SCHEDULED"&&!!post.scheduledAt&&post.scheduledAt<=new Date());return live?post:null;});}catch{return null;}}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const [post,settings]=await Promise.all([getPost(slug),getSiteSettings()]);if(!post)return{};const image=blogImageUrl(post);return {title:post.seoTitle||`${post.title} | ${settings.businessName}`,description:post.seoDescription||post.excerpt||settings.defaultSeoDescription,alternates:{canonical:post.canonicalUrl||`/blog/${post.slug}`},openGraph:{title:post.seoTitle||post.title,description:post.seoDescription||post.excerpt||undefined,type:"article",publishedTime:(post.publishedAt||post.scheduledAt)?.toISOString(),images:image?[{url:image,alt:post.featuredImageAlt||post.title}]:undefined}};}
export default async function BlogArticle({params}:Props){const {slug}=await params;const [post,settings]=await Promise.all([getPost(slug),getSiteSettings()]);if(!post)notFound();const image=blogImageUrl(post);const date=post.publishedAt||post.scheduledAt||post.createdAt;const site=(settings.websiteUrl||"https://www.heliosremedia.com").replace(/\/$/,"");const url=`${site}/blog/${post.slug}`;return <main className="min-h-screen bg-[#090909] text-white"><Navbar variant="solid"/><article><header className="container-shell pb-14 pt-40 sm:pb-20 sm:pt-48"><Link href="/blog" className="eyebrow text-[var(--helios-orange)]">← The journal</Link><p className="mt-10 text-[0.58rem] uppercase tracking-[0.18em] text-white/30">{post.category||"Insights"} · {new Intl.DateTimeFormat("en-US",{month:"long",day:"numeric",year:"numeric"}).format(date)} · {readingMinutes(post.content)} min read</p><h1 className="mt-6 max-w-5xl pb-[0.08em] font-display text-[clamp(3.6rem,7vw,7rem)] font-light leading-[0.9] tracking-[-0.05em]">{post.title}</h1>{post.excerpt&&<p className="mobile-summary mt-10 max-w-3xl text-lg leading-8 text-white/48">{post.excerpt}</p>}{post.author&&<p className="mt-7 text-xs uppercase tracking-[0.16em] text-white/28">By {post.author}</p>}</header>{image&&<div className="container-shell"><div className="relative aspect-[16/8.5] overflow-hidden"><Image src={image} alt={post.featuredImageAlt||post.title} fill priority className="object-cover"/></div></div>}<div className="container-shell grid gap-14 py-16 sm:py-24 lg:grid-cols-[minmax(0,46rem)_12rem] lg:justify-center"><BlogArticleBody content={post.content}/><aside><p className="text-[0.55rem] uppercase tracking-[0.16em] text-white/25">Share this story</p><ArticleShareLinks url={url} title={post.title}/>{post.sourceLinks&&Array.isArray(post.sourceLinks)&&post.sourceLinks.length>0&&<div className="mt-10 border-t border-white/10 pt-7"><p className="text-[0.55rem] uppercase tracking-[0.16em] text-white/25">Sources</p>{post.sourceLinks.filter((item):item is string=>typeof item==="string").map((source,index)=><a key={source} target="_blank" rel="noopener noreferrer" href={source} className="mt-3 block break-all text-xs leading-5 text-white/35">Source {index+1} ↗</a>)}</div>}</aside></div></article><Footer/></main>;}
