"use client";
import Link from "next/link";
import { useState } from "react";
type Maybe=number|null;
type Connection={id:string;platform:string;state:string;providerUsername:string|null;intendedAccountName:string|null;analyticsPermissionState:string;analyticsLastSuccessfulAt:string|null;analyticsLastAttemptAt:string|null;analyticsError:string|null};
type Post={id:string;campaignId:string;campaign:string;objective:string|null;sourceType:string;platform:string;postType:string;publishedAt:string|null;publicUrl:string|null;metrics:{reach:Maybe;impressions:Maybe;engagements:Maybe;engagementRate:Maybe;linkClicks:Maybe;videoViews:Maybe};definitions:Array<{name:string;definition:string}>};
const show=(value:Maybe)=>value===null?"Not Available":value.toLocaleString();
export default function SocialAnalytics({days,summary,briefing,connections,posts,recommendations}:{days:number;summary:{published:number;reach:Maybe;impressions:Maybe;engagements:Maybe;engagementRate:Maybe;linkClicks:Maybe;videoViews:Maybe};briefing:string;connections:Connection[];posts:Post[];recommendations:Array<Record<string,unknown>>}){
 const [busy,setBusy]=useState("");const [message,setMessage]=useState("");
 async function refresh(id:string){setBusy(id);const response=await fetch("/api/admin/social/analytics",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"refresh",connectionId:id,days})});const body=await response.json();setMessage(body.message||body.error);setBusy("");}
 return <div className="space-y-7 pb-12">
  <section className="flex flex-col gap-5 border-b border-white/[.08] pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-[var(--helios-orange)]">Verified performance</p><h1 className="mt-3 text-3xl font-light text-white sm:text-4xl">Social Analytics</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/40">Official provider data only. Unknown, unsupported, and unavailable metrics are never converted to zero.</p></div><div className="flex gap-2"><Link href="/admin/social-studio" className="admin-btn-secondary">Social Studio</Link><Link href={`/admin/social-studio/analytics/report?month=${new Date().toISOString().slice(0,7)}`} className="admin-btn-secondary">Monthly report</Link></div></section>
  <nav aria-label="Analytics date range" className="flex flex-wrap gap-2">{[7,30,90].map(value=><Link key={value} href={`/admin/social-studio/analytics?days=${value}`} className={days===value?"admin-btn-primary":"admin-btn-secondary"}>Last {value} days</Link>)}</nav>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4 xl:grid-cols-7">{[["Posts published",summary.published],["Reach",summary.reach],["Impressions",summary.impressions],["Supported engagement",summary.engagements],["Derived engagement rate",summary.engagementRate===null?null:Number(summary.engagementRate)],["Link clicks",summary.linkClicks],["Video views",summary.videoViews]].map(([label,value])=><div key={String(label)} className="rounded-xl border border-white/[.08] bg-white/[.025] p-4"><p className="text-[.58rem] uppercase tracking-[.14em] text-white/30">{label}</p><p className="mt-3 font-display text-2xl font-light text-white">{show(value as Maybe)}{label==="Derived engagement rate"&&value!==null?"%":""}</p></div>)}</section>
  <section className="rounded-2xl border border-[var(--helios-orange)]/20 bg-[var(--helios-orange)]/[.035] p-6"><p className="eyebrow text-[var(--helios-orange)]">Performance briefing</p><p className="mt-4 max-w-4xl text-sm leading-7 text-white/65">{briefing}</p><p className="mt-3 text-xs text-white/30">Grounded fallback briefing · AI regeneration is never automatic and cannot modify content.</p></section>
  <section className="rounded-2xl border border-white/[.08] bg-white/[.02] p-6"><h2 className="text-2xl font-light text-white">Connection and data health</h2><div className="mt-5 grid gap-3 lg:grid-cols-2">{connections.map(item=><article key={item.id} className="rounded-xl border border-white/[.08] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-white/75">{item.platform} · {item.providerUsername||item.intendedAccountName||"No account selected"}</p><p className="mt-1 text-xs text-white/35">{item.analyticsPermissionState.replaceAll("_"," ")}</p></div><button onClick={()=>refresh(item.id)} disabled={Boolean(busy)||!["CONNECTED","CONNECTED_DIRECT_PUBLISHING_DISABLED"].includes(item.state)} className="admin-btn-secondary">{busy===item.id?"Queued…":"Refresh data"}</button></div><p className="mt-3 text-xs text-white/30">Last successful refresh: {item.analyticsLastSuccessfulAt?new Date(item.analyticsLastSuccessfulAt).toLocaleString():"Never"}</p>{item.analyticsError&&<p className="mt-2 text-xs text-amber-200/70">{item.analyticsError}</p>}</article>)}{!connections.length&&<p className="text-sm text-white/35">No social accounts are connected. Analytics remain unavailable until an official connection is authorized.</p>}</div>{message&&<p role="status" aria-live="polite" className="mt-4 text-sm text-white/55">{message}</p>}</section>
  <section className="rounded-2xl border border-white/[.08] bg-white/[.02] p-6"><h2 className="text-2xl font-light text-white">Published post performance</h2><div className="mt-5 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-[.6rem] uppercase tracking-[.13em] text-white/30"><tr><th className="p-3">Campaign</th><th className="p-3">Platform / format</th><th className="p-3">Reach</th><th className="p-3">Engagement</th><th className="p-3">Views</th><th className="p-3">Action</th></tr></thead><tbody>{posts.map(item=><tr key={item.id} className="border-t border-white/[.06]"><td className="p-3 text-white/70">{item.campaign}</td><td className="p-3 text-white/45">{item.platform} · {item.postType.replaceAll("_"," ")}</td><td className="p-3 text-white/55">{show(item.metrics.reach)}</td><td className="p-3 text-white/55">{show(item.metrics.engagements)}</td><td className="p-3 text-white/55">{show(item.metrics.videoViews)}</td><td className="p-3"><Link href={`/admin/social-studio/analytics/posts/${item.id}`} className="text-[var(--helios-orange)]">View report</Link></td></tr>)}{!posts.length&&<tr><td colSpan={6} className="p-8 text-center text-white/30">No published posts are available in this reporting range.</td></tr>}</tbody></table></div></section>
  <section className="rounded-2xl border border-white/[.08] bg-white/[.02] p-6"><h2 className="text-2xl font-light text-white">Recommendations</h2><p className="mt-2 text-sm text-white/35">Recommendations require verified evidence and never schedule or publish automatically.</p><div className="mt-4 space-y-3">{recommendations.map(item=><article key={String(item.id)} className="rounded-xl border border-white/[.07] p-4"><p className="text-sm text-white/70">{String(item.title)}</p><p className="mt-2 text-xs leading-5 text-white/40">{String(item.recommendation)}</p><p className="mt-2 text-[.65rem] text-white/25">Sample: {String(item.sampleSize)} · {String(item.confidence)}</p></article>)}{!recommendations.length&&<p className="rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-white/30">More verified posts are needed before Social Studio can offer evidence-backed recommendations.</p>}</div></section>
 </div>;
}
